import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "android-app"


class AndroidAppStructureTest(unittest.TestCase):
    def test_android_project_files_exist(self) -> None:
        required = [
            "README.md",
            "settings.gradle.kts",
            "build.gradle.kts",
            "gradle.properties",
            "app/build.gradle.kts",
            "app/src/main/AndroidManifest.xml",
            "app/src/main/java/com/iwanttobeanifbbpro/app/MainActivity.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/SkillPromptBuilder.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/SkillAssetRepository.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/ProgressionAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseHistoryAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/DailyExecutionAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/MealAssemblyAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/SessionQualityAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/TrainingCloseoutAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/AiReviewActionAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/NextSetAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/WarmUpRampAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseSubstitutionAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/TomorrowCoachAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/WeeklyCheckInAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/BodyCompositionAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/ConditioningHydrationAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/PhysiqueMeasurementAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseVisualGuide.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/RecoveryAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/TrainingReadinessAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/network/OpenAiResponsesClient.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/data/DailyLog.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/data/DailyLogStore.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/data/AiReviewStore.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/data/AthleteProfile.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/data/TrainingPlan.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/data/TrainingPlanStore.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/DailySummaryBuilder.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/health/HealthSnapshot.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/health/HealthConnectRepository.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/ui/AppTheme.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/ui/CoachViewModel.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/ui/IfbbProCoachApp.kt",
        ]
        for relative in required:
            with self.subTest(relative=relative):
                self.assertTrue((APP / relative).exists(), relative)

    def test_app_embeds_skill_assets(self) -> None:
        asset_root = APP / "app/src/main/assets/skill"
        required_assets = [
            "SKILL.md",
            "references/evidence-map.md",
            "references/visual-analysis-and-food-estimation.md",
            "references/training-programming.md",
            "references/nutrition-body-composition.md",
            "references/session-execution-and-volume.md",
            "references/model-adaptation.md",
        ]
        for relative in required_assets:
            with self.subTest(relative=relative):
                self.assertTrue((asset_root / relative).exists(), relative)

    def test_api_client_supports_configurable_multimodal_responses_api(self) -> None:
        client = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/network/OpenAiResponsesClient.kt").read_text(
            encoding="utf-8"
        )
        expected_terms = [
            "/responses",
            "instructions",
            "input_image",
            "image_url",
            "promptLine(index",
            "data:",
            "output_text",
            "baseUrl",
            "apiKey",
            "model",
        ]
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, client)
        self.assertNotIn("sk-", client)

    def test_prompt_builder_exposes_skill_modes_and_linked_analysis(self) -> None:
        prompt = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/SkillPromptBuilder.kt").read_text(
            encoding="utf-8"
        )
        expected_terms = [
            "NEW_PLAN",
            "CHECK_IN",
            "TRAINING_VISUAL",
            "FOOD_VISUAL",
            "LINKED_TRAINING_NUTRITION",
            "evidence-map.md",
            "visual-analysis-and-food-estimation.md",
            "session-execution-and-volume.md",
            "nutrition-body-composition.md",
            "Exercise Substitution Coach",
            "Photo Evidence metadata",
            "exercise form frame",
            "physique progress photo",
            "same target muscle",
            "same movement pattern",
            "fatigue cost",
        ]
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, prompt)

    def test_daily_app_model_supports_training_nutrition_metrics_and_ai_review(self) -> None:
        model = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/DailyLog.kt").read_text(
            encoding="utf-8"
        )
        store = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/DailyLogStore.kt").read_text(
            encoding="utf-8"
        )
        plan_model = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/TrainingPlan.kt").read_text(
            encoding="utf-8"
        )
        log_model = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/DailyLog.kt").read_text(
            encoding="utf-8"
        )
        plan_store = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/TrainingPlanStore.kt").read_text(
            encoding="utf-8"
        )
        summary = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/DailySummaryBuilder.kt").read_text(
            encoding="utf-8"
        )
        ai_review_store = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/AiReviewStore.kt").read_text(
            encoding="utf-8"
        )
        athlete_profile = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/AthleteProfile.kt").read_text(
            encoding="utf-8"
        )
        expected_terms = [
            "AthleteProfile",
            "AthleteProfileStore",
            "athlete_profile",
            "primaryGoal",
            "currentPhase",
            "trainingExperience",
            "targetBodyFatPercent",
            "weeklyTrainingDays",
            "weakPoints",
            "constraints",
            "TrainingSession",
            "Daily Execution Plan",
            "DailyExecutionPlan",
            "DailyExecutionRoute",
            "dailyExecutionPlan",
            "priorityFocus",
            "primaryActionLabel",
            "primaryActionRoute",
            "trainingDecision",
            "nutritionDecision",
            "recoveryDecision",
            "dataQualityGate",
            "aiReviewGate",
            "planAdjustmentSignal",
            "nextBestAction",
            "Primary action",
            "Data quality gate",
            "AI review gate",
            "Plan adjustment signal",
            "ExerciseEntry",
            "SetEntry",
            "WeeklyTrainingPlan",
            "TrainingDay",
            "PlannedExercise",
            "TrainingPlanTemplate",
            "trainingPlanTemplates",
            "Beginner Full Body",
            "4-Day Hypertrophy",
            "5-Day Physique Priority",
            "Beginner Full Body Foundation",
            "4-Day Hypertrophy Builder",
            "5-Day Physique Priority",
            "fillWeek",
            "planned(",
            "TrainingPlanStore",
            "readPlan",
            "savePlan",
            "toExerciseEntry",
            "MealEntry",
            "PhotoEvidenceType",
            "PhotoEvidenceEntry",
            "photoEvidence",
            "Food or label photo",
            "Exercise form frame",
            "Equipment photo",
            "Physique progress photo",
            "Menu or nutrition label",
            "Daily photo evidence",
            "MealTemplate",
            "mealTemplates",
            "toMealEntry",
            "Lean Protein Bowl",
            "Pre-Workout Carbs",
            "Low-Fat Protein Fix",
            "Salmon Potato Plate",
            "Fiber + Micronutrient Add",
            "DailyMetrics",
            "DailyTargets",
            "DailyConditioning",
            "conditioning",
            "stepGoal",
            "cardioMinutes",
            "cardioType",
            "cardioIntensity",
            "waterLiters",
            "sodiumMg",
            "caffeineMg",
            "alcoholServings",
            "digestion",
            "AiReviewEntry",
            "AiReviewStore",
            "readReviews",
            "saveReview",
            "ai_review_history",
            "setEntries",
            "completedHardSets",
            "trainingVolumeKg",
            "restSeconds",
            "calories",
            "protein",
            "carbs",
            "fat",
            "bodyWeightKg",
            "bodyFatPercent",
            "leanBodyMassKg",
            "waistCm",
            "chestCm",
            "shoulderCm",
            "hipCm",
            "leftArmCm",
            "rightArmCm",
            "leftThighCm",
            "rightThighCm",
            "neckCm",
            "sleepHours",
            "restingHeartRateBpm",
            "totalCaloriesBurnedKcal",
            "healthDataSource",
            "healthSyncedAt",
            "readLog",
            "saveLog",
            "readRecentLogs",
            "log_date_index",
            "log_",
            "buildAiReviewContext",
            "daily training",
            "daily nutrition",
            "AI review",
            "Athlete profile and goal",
            "Interpret today's data through the athlete profile",
            "set-level performance",
            "rest time",
            "Current weekly training plan",
            "Template context",
            "Health Connect-derived data",
            "Recent trend window",
            "Weight change in window",
            "Daily trend rows",
            "Nutrition pacing",
            "Meal template context",
            "adherence",
            "Next meal focus",
            "Next Meal Builder",
            "NextMealBuilderSummary",
            "nextMealBuilderSummary",
            "Meal Assembly Guide",
            "MealAssemblyGuide",
            "mealAssemblyGuide",
            "promptLine",
            "Plate structure",
            "Protein anchor",
            "Carb anchor",
            "Fat control",
            "Fiber/micros",
            "Shopping cue",
            "Prep cue",
            "Photo/logging cue",
            "Avoid cue",
            "Macro target",
            "Timing cue",
            "Portion cue",
            "Photo/label cue",
            "Body composition guidance",
            "BodyCompositionGuidance",
            "bodyCompositionGuidance",
            "calorie adjustment",
            "target calories",
            "phaseGoal",
            "Physique Measurement Summary",
            "PhysiqueMeasurementSummary",
            "physiqueMeasurementSummary",
            "shoulder-to-waist ratio",
            "arm difference",
            "thigh difference",
            "Proportion cue",
            "Symmetry cue",
            "Tracking cue",
            "waist change",
            "chest change",
            "shoulder change",
            "hip change",
            "Recovery guidance",
            "RecoveryGuidance",
            "recoveryGuidance",
            "Conditioning & Hydration",
            "ConditioningHydrationGuidance",
            "conditioningHydrationGuidance",
            "step goal progress",
            "cardio status",
            "hydration status",
            "sodium cue",
            "caffeine cue",
            "weight fluctuation cue",
            "scale-weight noise",
            "NEAT behind",
            "Hydration gap",
            "Stimulant pressure",
            "water, sodium, caffeine, cardio, steps",
            "recommended training action",
            "recommendedTrainingAction",
            "readiness score",
            "readinessScore",
            "training pressure",
            "trainingPressure",
            "Controlled push",
            "Hold training stress",
            "Reduce volume",
            "Deload check",
            "Training Readiness Builder",
            "TrainingReadinessBuilder",
            "trainingReadinessBuilder",
            "Warm-up Ramp Plan",
            "WarmUpRampPlan",
            "WarmUpRampSet",
            "warmUpRampPlan",
            "ramp set checklist",
            "planned load percentage",
            "final ramp set quality",
            "first working set gate",
            "working-load gate",
            "Next Set Coach",
            "NextSetCoach",
            "nextSetCoach",
            "currentExerciseName",
            "current exercise",
            "next set target",
            "load cue",
            "reps cue",
            "RIR cue",
            "rest cue",
            "stop cue",
            "after-set logging cue",
            "Load cue",
            "Reps cue",
            "Rest cue",
            "Stop cue",
            "After-set logging cue",
            "Tomorrow Coach Brief",
            "TomorrowCoachBrief",
            "tomorrowCoachBrief",
            "tomorrowDate",
            "planDayName",
            "planFocus",
            "trainingAction",
            "nutritionAction",
            "recoveryAction",
            "trackingAction",
            "readinessGate",
            "tomorrow training focus",
            "tomorrow nutrition target",
            "tomorrow recovery gate",
            "tomorrow tracking action",
            "promptLine",
            "Weekly Check-in",
            "WeeklyCheckInSummary",
            "weeklyCheckInSummary",
            "trainingCompletionPercent",
            "planAdjustment",
            "nutritionAdjustment",
            "weakPointFocus",
            "dataQualityGate",
            "nextWeekAction",
            "Use Weekly Check-in before changing plan-wide volume or calorie targets",
            "Session Quality Dashboard",
            "SessionQualityDashboard",
            "sessionQualityDashboard",
            "Training Closeout Coach",
            "TrainingCloseoutCoach",
            "TrainingCloseoutTask",
            "trainingCloseoutCoach",
            "AI Review Action Queue",
            "AiReviewActionQueue",
            "AiReviewActionItem",
            "AiReviewActionCategory",
            "aiReviewActionQueue",
            "sourceLabel",
            "confidenceLabel",
            "primaryAction",
            "actionLabel",
            "Review saved guidance",
            "Run daily review",
            "training action",
            "nutrition action",
            "recovery action",
            "tracking action",
            "closeoutScore",
            "missingLogCount",
            "photoCue",
            "nutritionCue",
            "metricsCue",
            "sessionNoteCue",
            "AI review readiness",
            "missing set logs",
            "post-workout nutrition",
            "MuscleVolumeShare",
            "completionRatePercent",
            "loggedSetRatePercent",
            "averageRir",
            "painFlagCount",
            "techniqueFlagCount",
            "topMuscleVolumes",
            "qualityCue",
            "capacityCue",
            "riskCue",
            "Muscle volume",
            "Quality cue",
            "Capacity cue",
            "Risk cue",
            "Warm-up cue",
            "warmUpCue",
            "Ramp-up cue",
            "rampUpCue",
            "First working set",
            "firstWorkingSetCue",
            "Volume adjustment",
            "volumeAdjustmentCue",
            "Stop rule",
            "stopRule",
            "AI review focus",
            "aiReviewFocus",
            "Exercise visual guide",
            "Unified Exercise Visual Atlas",
            "Exercise Visual Legend",
            "统一动作图例",
            "visualPromptLine",
            "visual IDs",
            "equipment/action categories",
            "Chinese equipment labels",
            "unified instance diagrams",
            "three-step recognition",
            "ExerciseVisualAtlas",
            "exerciseVisualAtlas",
            "recognitionSteps",
            "recognitionFlow",
            "atlasLine",
            "action path cues",
            "quick visual cues",
            "find-equipment cues",
            "movement path cues",
            "beginner recognition cues",
            "equipment markers",
            "instance diagram cues",
            "common movements",
            "ExerciseVisualSpec",
            "ExerciseVisualType",
            "exerciseVisualLibrarySpecs",
            "visualId",
            "figureTitle",
            "actionPathCue",
            "quickVisualCue",
            "findEquipmentCue",
            "movementPathCue",
            "beginnerCue",
            "equipmentMarkers",
            "VG-01",
            "VG-10",
            "equipmentZh",
            "instanceCue",
            "commonMovements",
            "Adjustable bench",
            "Pull-up/Dip station",
            "Resistance band",
            "Leg press or hack squat",
            "Progression cue",
            "Use each Progression Cue",
            "progressionCue",
            "Exercise Substitution Coach",
            "ExerciseSubstitutionGuide",
            "ExerciseSubstitutionOption",
            "exerciseSubstitutionGuide",
            "equipment unavailable",
            "primaryOption",
            "secondaryOptions",
            "same target muscle",
            "same movement pattern",
            "preserve rep range",
            "fatigue cost",
            "keepIntentCue",
            "loadAdjustmentCue",
            "visual guide ID",
            "Exercise history",
            "Compare Exercise History",
            "exerciseHistorySummary",
            "previous volume",
            "current volume",
            "best load",
            "best reps",
            "average RIR",
        ]
        progression = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ProgressionAdvisor.kt").read_text(
            encoding="utf-8"
        )
        history = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseHistoryAdvisor.kt").read_text(
            encoding="utf-8"
        )
        body_composition = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/BodyCompositionAdvisor.kt"
        ).read_text(encoding="utf-8")
        physique_measurement = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/PhysiqueMeasurementAdvisor.kt"
        ).read_text(encoding="utf-8")
        daily_execution = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/DailyExecutionAdvisor.kt"
        ).read_text(encoding="utf-8")
        meal_assembly = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/MealAssemblyAdvisor.kt"
        ).read_text(encoding="utf-8")
        session_quality = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/SessionQualityAdvisor.kt"
        ).read_text(encoding="utf-8")
        training_closeout = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/TrainingCloseoutAdvisor.kt"
        ).read_text(encoding="utf-8")
        ai_review_action = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/AiReviewActionAdvisor.kt"
        ).read_text(encoding="utf-8")
        recovery = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/RecoveryAdvisor.kt").read_text(
            encoding="utf-8"
        )
        conditioning = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ConditioningHydrationAdvisor.kt"
        ).read_text(encoding="utf-8")
        training_readiness = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/TrainingReadinessAdvisor.kt"
        ).read_text(encoding="utf-8")
        next_set = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/NextSetAdvisor.kt"
        ).read_text(encoding="utf-8")
        warm_ramp = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/WarmUpRampAdvisor.kt"
        ).read_text(encoding="utf-8")
        tomorrow = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/TomorrowCoachAdvisor.kt"
        ).read_text(encoding="utf-8")
        weekly_checkin = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/WeeklyCheckInAdvisor.kt"
        ).read_text(encoding="utf-8")
        substitution = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseSubstitutionAdvisor.kt"
        ).read_text(encoding="utf-8")
        visual = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseVisualGuide.kt").read_text(
            encoding="utf-8"
        )
        combined = f"{model}\n{store}\n{ai_review_store}\n{athlete_profile}\n{plan_model}\n{plan_store}\n{summary}\n{progression}\n{history}\n{body_composition}\n{physique_measurement}\n{daily_execution}\n{meal_assembly}\n{session_quality}\n{training_closeout}\n{ai_review_action}\n{recovery}\n{conditioning}\n{training_readiness}\n{next_set}\n{warm_ramp}\n{tomorrow}\n{weekly_checkin}\n{substitution}\n{visual}"
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, combined)

    def test_ui_exposes_daily_workflows(self) -> None:
        ui = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/ui/IfbbProCoachApp.kt").read_text(
            encoding="utf-8"
        )
        view_model = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/ui/CoachViewModel.kt").read_text(
            encoding="utf-8"
        )
        plan_model = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/TrainingPlan.kt").read_text(
            encoding="utf-8"
        )
        log_model = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/DailyLog.kt").read_text(
            encoding="utf-8"
        )
        expected_terms = [
            "Today",
            "Plan",
            "Training",
            "Nutrition",
            "Metrics",
            "AI Coach",
            "AppLanguage",
            "appLanguage",
            "updateLanguage",
            "loadLanguage",
            "saveLanguage",
            "localizedTitle",
            "Start Here",
            "从这里开始",
            "DailyStartStep",
            "dailyStartSteps",
            "StartHereCoachCard",
            "StartHereStepRow",
            "EN",
            "中文",
            "AiSettings",
            "isConfigured",
            "AiSetupStatus",
            "aiSetupStatus",
            "AiSetupStatusCard",
            "AI Setup & Review Readiness",
            "Set API first",
            "Missing setup",
            "AI review ready",
            "Photo context linked",
            "AI setup is not ready",
            "addExercise",
            "addMeal",
            "addMealTemplate",
            "updateMetrics",
            "updateTargets",
            "updateConditioning",
            "runDailyReview",
            "hard sets",
            "meal photo",
            "PhotoEvidenceCard",
            "PhotoEvidenceType",
            "Photo Evidence",
            "Photo purpose",
            "Form photo",
            "Equipment photo",
            "Progress photo",
            "Food or label photo",
            "Exercise form frame",
            "Physique progress photo",
            "addPreparedImages",
            "preparePhotoEvidence",
            "pendingPhotoType",
            "pendingPhotoNote",
            "Rest timer",
            "Complete",
            "AI Data Map",
            "Set load",
            "Actual reps",
            "Weekly Plan",
            "Plan Templates",
            "PlanTemplateLibrary",
            "PlanTemplateCard",
            "applyTrainingPlanTemplate",
            "trainingPlanTemplates",
            "Beginner Full Body",
            "4-Day Hypertrophy",
            "5-Day Physique Priority",
            "Use",
            "Current",
            "Athlete Profile",
            "Primary physique goal",
            "Weak points or physique priorities",
            "updateAthleteProfile",
            "athleteProfile",
            "Apply today",
            "addPlannedExercise",
            "applyPlanDayToToday",
            "Health Connect",
            "Connect health data",
            "Sync today",
            "Body fat",
            "Resting HR",
            "healthPermissions",
            "syncHealthData",
            "IfbbProTheme",
            "AppleInspiredLightColors",
            "Scaffold",
            "NavigationBar",
            "NavigationBarItem",
            "Command Center",
            "Daily Execution Plan",
            "DailyExecutionPlan",
            "DailyExecutionPlanCard",
            "DailyExecutionRoute",
            "dailyExecutionPlan",
            "Priority",
            "Priority focus",
            "Primary action",
            "Data quality gate",
            "AI review gate",
            "Plan adjustment signal",
            "Daily Coach Checklist",
            "DailyCoachTask",
            "dailyCoachTasks",
            "DailyCoachChecklistCard",
            "plan, train, eat, sync",
            "Plan prepared",
            "Training executed",
            "Food logged",
            "Metrics synced",
            "AI review locked",
            "Run review",
            "View review",
            "Beginner Friendly Flow",
            "Readiness",
            "Today Snapshot",
            "dailyReadiness",
            "recentLogs",
            "7-Day Trend",
            "TrendOverviewCard",
            "reviewHistory",
            "Saved AI Reviews",
            "Latest AI guidance",
            "ReviewHistoryCard",
            "AI Review Action Queue",
            "AiReviewActionQueueCard",
            "AiReviewActionRow",
            "performAiReviewAction",
            "sourceLabel",
            "confidenceLabel",
            "primaryAction",
            "actionLabel",
            "Review saved guidance",
            "Run daily review",
            "training action",
            "nutrition action",
            "recovery action",
            "tracking action",
            "plan action",
            "Xiaomi/Mi Fitness -> Health Connect",
            "Huawei Health -> Health Connect or Health Kit",
            "Scale/watch/phone -> Health Connect",
            "Manual fallback",
            "Today Visual Primer",
            "TodayExerciseVisualPrimerCard",
            "ExerciseVisualGuide",
            "ExerciseVisualGuideLibrary",
            "ExerciseVisualGuideSample",
            "ExerciseVisualLegendGrid",
            "ExerciseVisualLegendTile",
            "ExerciseVisualMap",
            "ExerciseVisualMapItem",
            "ExerciseVisualMapRow",
            "ExerciseVisualHeader",
            "ExerciseVisualType",
            "drawExerciseVisual",
            "Exercise visual guide",
            "Selected Day Visual Map",
            "Today's Exercise Visual Map",
            "thumbnail",
            "统一动作图例",
            "Visual guide ID",
            "Unified instance diagram",
            "Unified Exercise Visual Atlas",
            "Three-step recognition",
            "Simplified instance diagram",
            "Find real equipment",
            "Movement path matching",
            "Action path cue",
            "Quick visual cue",
            "Find equipment cue",
            "Movement path cue",
            "Beginner recognition cue",
            "Equipment markers",
            "Exercise Visual Library",
            "ExerciseVisualAtlasOverview",
            "ExerciseVisualRecognitionPreview",
            "Live equipment/action preview",
            "Chinese equipment labels",
            "visualId",
            "figureTitle",
            "actionPathCue",
            "quickVisualCue",
            "findEquipmentCue",
            "movementPathCue",
            "beginnerCue",
            "equipmentMarkers",
            "VG-01",
            "VG-10",
            "Instance diagram cue",
            "Common movement examples",
            "Equipment photo recognition",
            "Exercise name -> visual category",
            "simple equipment/action instance diagrams",
            "equipment/action thumbnails",
            "equipmentZh",
            "instanceCue",
            "commonMovements",
            "史密斯机",
            "哑铃",
            "Smith machine",
            "Cable station",
            "Dumbbells",
            "Barbell",
            "Machine",
            "Bodyweight or open station",
            "Adjustable bench",
            "Pull-up/Dip station",
            "Resistance band",
            "Leg press or hack squat",
            "Example: ${spec.example}",
            "Look for two rails and a fixed bar",
            "Look for a cable, pulley, and handle",
            "Look for a flat or adjustable bench",
            "Look for an overhead bar, dip handles, or assist platform",
            "Look for a band anchored to a rack, door, or post",
            "Look for a sled platform, seat, and safety handles",
            "equipment/action instance diagrams",
            "Chinese equipment labels",
            "Instance diagram cue",
            "Common movement examples",
            "Dumbbell Row",
            "Barbell Squat",
            "Machine Chest Press",
            "Incline Dumbbell Press",
            "Band Face Pull",
            "Leg Press",
            "NutritionPacing",
            "Nutrition Pacing",
            "NextMealBuilder",
            "Next Meal Builder",
            "NextMealBuilderCard",
            "nextMealBuilder",
            "MealAssemblyGuide",
            "Meal Assembly Guide",
            "MealAssemblyGuideCard",
            "mealAssemblyGuide",
            "Plate structure",
            "Protein anchor",
            "Carb anchor",
            "Fat control",
            "Fiber/micros",
            "Shopping cue",
            "Prep cue",
            "Photo/logging cue",
            "Next meal macro targets",
            "Meal timing cue",
            "Portion uncertainty cue",
            "MealTemplate",
            "Meal Templates",
            "MealTemplateLibrary",
            "MealTemplateCard",
            "mealTemplates",
            "Lean Protein Bowl",
            "Pre-Workout Carbs",
            "Low-Fat Protein Fix",
            "Salmon Potato Plate",
            "Fiber + Micronutrient Add",
            "BodyCompositionGuidance",
            "Body Composition Guidance",
            "BodyCompositionCard",
            "bodyCompositionGuidance",
            "PhysiqueMeasurementSummary",
            "Physique Measurement Summary",
            "PhysiqueMeasurementSummaryCard",
            "physiqueMeasurementSummary",
            "Physique Measurements",
            "Chest cm",
            "Shoulder cm",
            "Hip cm",
            "Left arm cm",
            "Right arm cm",
            "Left thigh cm",
            "Right thigh cm",
            "Neck cm",
            "shoulder-to-waist ratio",
            "arm symmetry",
            "thigh symmetry",
            "V-taper direction",
            "Small calorie increase",
            "Small calorie decrease",
            "Hold targets",
            "Need trend data",
            "Kcal adjust",
            "Weight trend",
            "RecoveryGuidance",
            "Recovery Guidance",
            "RecoveryGuidanceCard",
            "recoveryGuidance",
            "ConditioningHydrationGuidance",
            "Conditioning & Hydration",
            "ConditioningHydrationCard",
            "conditioningHydrationGuidance",
            "DailyConditioning",
            "Step goal",
            "Cardio min",
            "Cardio type",
            "Intensity",
            "Water L",
            "Sodium mg",
            "Caffeine mg",
            "Alcohol",
            "Digestion, bloating, high-salt meal, cramps, pump",
            "scale-weight noise",
            "Training action",
            "Sleep signal",
            "HR signal",
            "Controlled push",
            "Hold training stress",
            "Reduce volume",
            "Deload check",
            "TrainingReadinessBuilder",
            "TrainingReadinessBuilderCard",
            "trainingReadinessBuilder",
            "Training Readiness Builder",
            "WarmUpRampPlan",
            "WarmUpRampSet",
            "WarmUpRampPlanCard",
            "warmUpRampPlan",
            "Warm-up Ramp Plan",
            "Ramp set checklist",
            "planned load percentage",
            "final ramp set quality",
            "first working set gate",
            "NextSetCoach",
            "NextSetCoachCard",
            "nextSetCoach",
            "Next Set Coach",
            "Current exercise",
            "Next set target",
            "Load cue",
            "Reps/RIR",
            "Rest cue",
            "Execution cue",
            "Stop cue",
            "After-set logging cue",
            "TomorrowCoachBrief",
            "TomorrowCoachBriefCard",
            "tomorrowCoachBrief",
            "Tomorrow Coach Brief",
            "Tomorrow training focus",
            "Tomorrow nutrition target",
            "Tomorrow recovery gate",
            "Tomorrow tracking action",
            "Plan tomorrow",
            "Food targets",
            "Readiness gate",
            "WeeklyCheckInSummary",
            "WeeklyCheckInCard",
            "weeklyCheckInSummary",
            "Weekly Check-in",
            "Training completion",
            "Plan adjustment",
            "Nutrition adjustment",
            "Weak point",
            "Next week action",
            "SessionQualityDashboard",
            "SessionQualityDashboardCard",
            "sessionQualityDashboard",
            "Session Quality Dashboard",
            "TrainingCloseoutCoach",
            "TrainingCloseoutTask",
            "TrainingCloseoutCoachCard",
            "trainingCloseoutCoach",
            "Training Closeout Coach",
            "Closeout",
            "Missing logs",
            "Finish sets",
            "Complete set logs",
            "Add form evidence",
            "Log post-workout food",
            "Sync recovery metrics",
            "AI review readiness",
            "photo evidence cue",
            "post-workout nutrition cue",
            "metrics sync cue",
            "Completion rate",
            "Logged set rate",
            "Average RIR",
            "Muscle volume distribution",
            "Pain flags",
            "Technique flags",
            "qualityCue",
            "capacityCue",
            "riskCue",
            "Warm-up cue",
            "Ramp-up cue",
            "First working set",
            "Volume adjustment",
            "Stop rule",
            "Recovery gate",
            "warmUpCue",
            "rampUpCue",
            "firstWorkingSetCue",
            "volumeAdjustmentCue",
            "stopRule",
            "nextMealFocus",
            "Next meal focus",
            "formatRemaining",
            "$unit left",
            "over",
            "adherenceScore",
            "ProgressionCue",
            "Progression Cue",
            "ExerciseSubstitutionGuide",
            "ExerciseSubstitutionCard",
            "Exercise Substitution Coach",
            "exerciseSubstitutionGuide",
            "equipment unavailable",
            "trigger reason",
            "primaryOption",
            "secondaryOptions",
            "same target muscle",
            "same movement pattern",
            "preserve rep range",
            "fatigue cost",
            "keepIntentCue",
            "loadAdjustmentCue",
            "ExerciseHistorySummary",
            "ExerciseHistoryCard",
            "Exercise History",
            "exerciseHistorySummary",
            "First tracked session",
            "Volume up",
            "Volume down",
            "Load PR",
            "Rep PR",
            "Matched last time",
            "Last volume",
            "Today volume",
            "Best load",
            "Best reps",
            "Avg RIR",
            "Add reps first",
            "Add load next time",
            "Hold load",
            "Modify or hold",
            "Finish baseline",
            "hasPainSignal",
            "no pain",
        ]
        activity = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/MainActivity.kt").read_text(encoding="utf-8")
        theme = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/ui/AppTheme.kt").read_text(encoding="utf-8")
        progression = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ProgressionAdvisor.kt").read_text(
            encoding="utf-8"
        )
        history = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseHistoryAdvisor.kt").read_text(
            encoding="utf-8"
        )
        body_composition = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/BodyCompositionAdvisor.kt"
        ).read_text(encoding="utf-8")
        physique_measurement = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/PhysiqueMeasurementAdvisor.kt"
        ).read_text(encoding="utf-8")
        daily_execution = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/DailyExecutionAdvisor.kt"
        ).read_text(encoding="utf-8")
        meal_assembly = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/MealAssemblyAdvisor.kt"
        ).read_text(encoding="utf-8")
        session_quality = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/SessionQualityAdvisor.kt"
        ).read_text(encoding="utf-8")
        training_closeout = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/TrainingCloseoutAdvisor.kt"
        ).read_text(encoding="utf-8")
        ai_review_action = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/AiReviewActionAdvisor.kt"
        ).read_text(encoding="utf-8")
        recovery = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/RecoveryAdvisor.kt").read_text(
            encoding="utf-8"
        )
        conditioning = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ConditioningHydrationAdvisor.kt"
        ).read_text(encoding="utf-8")
        training_readiness = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/TrainingReadinessAdvisor.kt"
        ).read_text(encoding="utf-8")
        next_set = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/NextSetAdvisor.kt"
        ).read_text(encoding="utf-8")
        warm_ramp = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/WarmUpRampAdvisor.kt"
        ).read_text(encoding="utf-8")
        tomorrow = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/TomorrowCoachAdvisor.kt"
        ).read_text(encoding="utf-8")
        weekly_checkin = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/WeeklyCheckInAdvisor.kt"
        ).read_text(encoding="utf-8")
        substitution = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseSubstitutionAdvisor.kt"
        ).read_text(encoding="utf-8")
        visual = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseVisualGuide.kt").read_text(
            encoding="utf-8"
        )
        combined = f"{ui}\n{view_model}\n{plan_model}\n{log_model}\n{activity}\n{theme}\n{progression}\n{history}\n{body_composition}\n{physique_measurement}\n{daily_execution}\n{meal_assembly}\n{session_quality}\n{training_closeout}\n{ai_review_action}\n{recovery}\n{conditioning}\n{training_readiness}\n{next_set}\n{warm_ramp}\n{tomorrow}\n{weekly_checkin}\n{substitution}\n{visual}"
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, combined)

    def test_health_connect_integration_is_structured_and_permissioned(self) -> None:
        gradle = (APP / "app/build.gradle.kts").read_text(encoding="utf-8")
        manifest = (APP / "app/src/main/AndroidManifest.xml").read_text(encoding="utf-8")
        repository = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/health/HealthConnectRepository.kt"
        ).read_text(encoding="utf-8")
        snapshot = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/health/HealthSnapshot.kt").read_text(
            encoding="utf-8"
        )
        expected_terms = [
            "androidx.health.connect:connect-client",
            "android.permission.health.READ_WEIGHT",
            "android.permission.health.READ_BODY_FAT",
            "android.permission.health.READ_STEPS",
            "android.permission.health.READ_SLEEP",
            "android.permission.health.READ_RESTING_HEART_RATE",
            "com.google.android.apps.healthdata",
            "android.permission.START_VIEW_PERMISSION_USAGE",
            "android.intent.action.VIEW_PERMISSION_USAGE",
            "android.intent.category.HEALTH_PERMISSIONS",
            "HealthConnectClient",
            "import androidx.health.connect.client.PermissionController",
            "PermissionController.createRequestPermissionResultContract",
            "HealthPermission.getReadPermission",
            "WeightRecord",
            "BodyFatRecord",
            "LeanBodyMassRecord",
            "StepsRecord",
            "SleepSessionRecord",
            "RestingHeartRateRecord",
            "TotalCaloriesBurnedRecord",
            "AggregateRequest",
            "ReadRecordsRequest",
            "HealthSnapshot",
            "hasImportableMetrics",
            "Xiaomi",
            "Huawei",
            "source app writes compatible records into Health Connect",
        ]
        combined = f"{gradle}\n{manifest}\n{repository}\n{snapshot}"
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, combined)

    def test_readme_documents_build_and_api_setup(self) -> None:
        readme = (APP / "README.md").read_text(encoding="utf-8")
        expected_terms = [
            "Android Studio",
            "JDK 17",
            "API key",
            "base URL",
            "model",
            "OpenAI Responses API",
            "photos",
            "Photo Evidence",
            "classified photos",
            "food, form, equipment, label, or physique progress",
            "Food or label photo",
            "Exercise form frame",
            "Equipment photo",
            "Physique progress photo",
            "skill assets",
            "daily training",
            "daily nutrition",
            "AI review",
            "rest countdown",
            "set-level",
            "AI Data Map",
            "weekly training plan",
            "Plan Templates",
            "Beginner Full Body",
            "4-Day Hypertrophy",
            "5-Day Physique Priority",
            "Apply today",
            "Health Connect",
            "Xiaomi",
            "Mi Fitness",
            "Huawei",
            "body fat",
            "resting heart rate",
            "Huawei Health Kit",
            "Athlete Profile",
            "target weight/body fat",
            "weekly training days",
            "manual entry",
            "EN/中文 language switching",
            "AppLanguage",
            "updateLanguage",
            "loadLanguage",
            "Start Here",
            "DailyStartStep",
            "StartHereCoachCard",
            "StartHereStepRow",
            "plan, train, log food, sync health data, then run AI review",
            "AI Setup & Review Readiness",
            "AiSetupStatus",
            "AiSetupStatusCard",
            "AiSettings.isConfigured()",
            "missing setup",
            "AI review ready",
            "photo context",
            "unified exercise visual guide",
            "Exercise Visual Library",
            "Smith machine",
            "cable station",
            "dumbbells",
            "barbell",
            "machine",
            "adjustable bench",
            "pull-up/dip station",
            "resistance band",
            "leg press or hack squat",
            "bodyweight/open-station",
            "Chinese equipment labels",
            "instance diagram cues",
            "visual guide IDs",
            "unified instance diagrams",
            "action path cues",
            "quick visual cues",
            "find-equipment cues",
            "movement path cues",
            "beginner recognition cues",
            "equipment markers",
            "common movement examples",
            "live equipment/action preview",
            "example movement",
            "look-for cue",
            "Nutrition Pacing",
            "Next Meal Builder",
            "next practical meal target",
            "meal timing cue",
            "portion uncertainty cue",
            "Meal Assembly Guide",
            "plate structure",
            "protein anchor",
            "carb anchor",
            "fat control",
            "shopping cue",
            "prep cue",
            "photo/logging cue",
            "Meal Templates",
            "Lean Protein Bowl",
            "Pre-Workout Carbs",
            "Low-Fat Protein Fix",
            "remaining or over target",
            "macro adherence score",
            "next-meal focus",
            "Body Composition Guidance",
            "small calorie adjustment",
            "Physique Measurement Summary",
            "waistCm",
            "chestCm",
            "shoulderCm",
            "hipCm",
            "leftArmCm",
            "rightArmCm",
            "leftThighCm",
            "rightThighCm",
            "neckCm",
            "shoulder-to-waist ratio",
            "arm symmetry",
            "thigh symmetry",
            "Recovery Guidance",
            "training-pressure guidance",
            "Daily Execution Plan",
            "priority focus",
            "primary action",
            "data quality gate",
            "AI review gate",
            "plan adjustment signal",
            "Training Readiness Builder",
            "Warm-up Ramp Plan",
            "ramp set checklist",
            "planned load percentages",
            "final ramp set quality",
            "first working set gate",
            "Next Set Coach",
            "current exercise",
            "next set target",
            "load cue",
            "reps cue",
            "RIR cue",
            "rest cue",
            "stop cue",
            "after-set logging cue",
            "Tomorrow Coach Brief",
            "Weekly Check-in",
            "training completion",
            "average calories/protein",
            "weight change",
            "recovery average",
            "weak-point focus",
            "next-week action",
            "tomorrow training focus",
            "tomorrow nutrition target",
            "tomorrow recovery gate",
            "tomorrow tracking action",
            "readiness gate",
            "Session Quality Dashboard",
            "Training Closeout Coach",
            "closeout score",
            "missing set logs",
            "photo evidence cue",
            "post-workout nutrition cue",
            "metrics sync cue",
            "AI review readiness",
            "completion rate",
            "logged set rate",
            "average RIR",
            "muscle-volume distribution",
            "pain flags",
            "technique flags",
            "warm-up strategy",
            "first working set",
            "volume adjustment",
            "stop rule",
            "reduce volume",
            "deload check",
            "Progression Cue",
            "Exercise Substitution Coach",
            "primaryOption",
            "secondaryOptions",
            "same target muscle",
            "same movement pattern",
            "preserve rep range",
            "fatigue cost",
            "keepIntentCue",
            "loadAdjustmentCue",
            "visual guide ID continuity",
            "Exercise History",
            "previous/current volume",
            "best load",
            "best reps",
            "average RIR",
            "add reps",
            "add load",
            "hold",
            "modify",
        ]
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, readme)

    def test_static_ui_preview_covers_core_app_workflows(self) -> None:
        html_path = APP / "preview/index.html"
        readme_path = APP / "preview/README.md"
        self.assertTrue(html_path.exists(), "preview/index.html")
        self.assertTrue(readme_path.exists(), "preview/README.md")
        html = html_path.read_text(encoding="utf-8")
        readme = readme_path.read_text(encoding="utf-8")
        expected_terms = [
            "Live design preview",
            "Apple",
            "Today",
            "EN/中文",
            "Language switch",
            "language-toggle",
            "Start Here / 从这里开始",
            "DailyStartStep",
            "StartHereCoachCard",
            "StartHereStepRow",
            "AppLanguage",
            "updateLanguage",
            "AI Setup & Review Readiness",
            "AiSetupStatus",
            "AiSetupStatusCard",
            "isConfigured",
            "Set API first",
            "Missing setup",
            "AI review ready",
            "Photo context linked",
            "Command Center",
            "Daily Execution Plan",
            "Priority",
            "Primary",
            "Data quality gate",
            "AI review gate",
            "Plan adjustment signal",
            "Athlete Profile",
            "Plan Templates",
            "Beginner Full Body",
            "4-Day Hypertrophy",
            "5-Day Physique Priority",
            "Weekly Plan",
            "Training Execution",
            "Training Readiness Builder",
            "Warm-up Ramp Plan",
            "ramp set checklist",
            "planned load percentages",
            "final ramp set quality",
            "first working set gate",
            "Next Set Coach",
            "Current exercise",
            "Next set target",
            "Load cue",
            "RIR cue",
            "Rest cue",
            "Stop cue",
            "After-set logging cue",
            "Tomorrow Coach Brief",
            "Weekly Check-in",
            "Training completion",
            "Recovery average",
            "Weak-point focus",
            "Next week action",
            "Tomorrow training focus",
            "Tomorrow nutrition target",
            "Tomorrow recovery gate",
            "Tomorrow tracking action",
            "Readiness gate",
            "Session Quality Dashboard",
            "Training Closeout Coach",
            "closeout score",
            "missing set logs",
            "photo evidence cue",
            "post-workout nutrition cue",
            "metrics sync cue",
            "AI review readiness",
            "Completion rate",
            "Logged set rate",
            "Average RIR",
            "Muscle volume distribution",
            "Pain flags",
            "Technique flags",
            "Warm-up cue",
            "Ramp-up cue",
            "First working set",
            "Volume adjustment",
            "Stop rule",
            "Rest timer",
            "Nutrition",
            "Meal Templates",
            "Lean Protein Bowl",
            "Pre-Workout Carbs",
            "Low-Fat Protein Fix",
            "Health Connect",
            "Xiaomi/Mi Fitness -> Health Connect",
            "Huawei Health -> Health Connect or Health Kit",
            "AI Review Action Queue",
            "sourceLabel",
            "confidenceLabel",
            "primaryAction",
            "actionLabel",
            "training action",
            "nutrition action",
            "recovery action",
            "tracking action",
            "plan action",
            "AI Coach",
            "AI Data Map",
            "Photo Evidence",
            "Photo purpose",
            "Food or label photo",
            "Exercise form frame",
            "Equipment photo",
            "Physique progress photo",
            "Menu or nutrition label",
            "Classified photos",
            "Saved AI Reviews",
            "Daily Coach Checklist",
            "Plan prepared",
            "Training executed",
            "Food logged",
            "Metrics synced",
            "AI review locked",
            "Exercise visual guide",
            "Exercise Visual Library",
            "Exercise Visual Legend",
            "统一动作图例",
            "legend-grid",
            "legend-tile",
            "Today Visual Primer",
            "Selected Day Visual Map",
            "Today's Exercise Visual Map",
            "exercise thumbnail headers",
            "Live equipment/action preview",
            "Chinese equipment labels",
            "Visual guide ID",
            "Unified instance diagram",
            "Unified Exercise Visual Atlas",
            "Three-step recognition",
            "Simplified instance diagram",
            "Find real equipment",
            "Movement path matching",
            "Action path cue",
            "Quick visual cue",
            "Find equipment cue",
            "Movement path cue",
            "Beginner recognition cue",
            "Equipment markers",
            "Instance diagram cue",
            "Common movement examples",
            "Equipment photo recognition",
            "Exercise name -> visual category",
            "simple equipment/action instance diagrams",
            "visual-map thumbnails",
            "VG-01",
            "VG-10",
            "Smith machine",
            "Cable station",
            "Dumbbells",
            "Barbell",
            "Machine",
            "Adjustable bench",
            "Pull-up/Dip station",
            "Resistance band",
            "Leg press or hack squat",
            "Bodyweight or open station",
            "Guided press path",
            "Pulley resistance",
            "Example: Incline Smith Press",
            "史密斯机",
            "哑铃",
            "Smith Squat",
            "Dumbbell Press",
            "Look for two rails and a fixed bar",
            "Unified exercise visual guide",
            "equipment/action instance diagrams",
            "Unified Exercise Visual Atlas",
            "Three-step recognition",
            "Simplified instance diagram",
            "Find real equipment",
            "Movement path matching",
            "Nutrition Pacing",
            "Next Meal Builder",
            "Next meal macro targets",
            "Meal Assembly Guide",
            "Plate structure",
            "Protein anchor",
            "Carb anchor",
            "Fat control",
            "Fiber/micros",
            "Shopping cue",
            "Prep cue",
            "Photo/logging cue",
            "Meal timing cue",
            "Portion uncertainty cue",
            "Meal Templates",
            "Body Composition Guidance",
            "Physique Measurement Summary",
            "Physique Measurements",
            "Chest cm",
            "Shoulder cm",
            "Left arm cm",
            "Right thigh cm",
            "shoulder-to-waist ratio",
            "arm symmetry",
            "thigh symmetry",
            "Recovery Guidance",
            "Training Readiness Builder",
            "Warm-up Ramp Plan",
            "Warm-up cue",
            "Ramp-up cue",
            "Ramp set checklist",
            "planned load percentage",
            "final ramp set quality",
            "first working set gate",
            "First working set",
            "Volume adjustment",
            "Stop rule",
            "Training action",
            "Sleep signal",
            "HR signal",
            "Hold targets",
            "Kcal adjust",
            "Weight trend",
            "Next meal focus",
            "Nutrition totals + pacing",
            "Body Composition Guidance",
            "Protein behind",
            "Progression Cue",
            "Exercise Substitution Coach",
            "equipment unavailable",
            "trigger reason",
            "primaryOption",
            "secondaryOptions",
            "same target muscle",
            "same movement pattern",
            "preserve rep range",
            "fatigue cost",
            "keepIntentCue",
            "loadAdjustmentCue",
            "Exercise History",
            "Add reps first",
            "Last volume",
            "Today volume",
            "Best load",
            "Best reps",
            "Avg RIR",
            "previous/current volume",
            "data-tab",
            "complete-set",
            "setInterval",
            "Open `index.html`",
        ]
        combined = f"{html}\n{readme}"
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, combined)

    def test_skill_assets_define_exercise_visual_guide_categories(self) -> None:
        skill_library = (ROOT / "skills/i-want-to-be-an-ifbb-pro/references/exercise-library.md").read_text(
            encoding="utf-8"
        )
        app_library = (APP / "app/src/main/assets/skill/references/exercise-library.md").read_text(
            encoding="utf-8"
        )
        visual_analysis = (
            ROOT / "skills/i-want-to-be-an-ifbb-pro/references/visual-analysis-and-food-estimation.md"
        ).read_text(encoding="utf-8")
        app_visual_analysis = (
            APP / "app/src/main/assets/skill/references/visual-analysis-and-food-estimation.md"
        ).read_text(encoding="utf-8")
        nutrition_body_composition = (
            ROOT / "skills/i-want-to-be-an-ifbb-pro/references/nutrition-body-composition.md"
        ).read_text(encoding="utf-8")
        app_nutrition_body_composition = (
            APP / "app/src/main/assets/skill/references/nutrition-body-composition.md"
        ).read_text(encoding="utf-8")
        session_execution = (
            ROOT / "skills/i-want-to-be-an-ifbb-pro/references/session-execution-and-volume.md"
        ).read_text(encoding="utf-8")
        app_session_execution = (
            APP / "app/src/main/assets/skill/references/session-execution-and-volume.md"
        ).read_text(encoding="utf-8")
        expected_terms = [
            "Exercise Visual Guide",
            "Chinese equipment labels",
            "simple instance diagrams",
            "Unified Exercise Visual Atlas",
            "three-step recognition",
            "Match the simplified instance diagram",
            "Find the real equipment markers",
            "Follow the intended movement path",
            "quick visual cues",
            "find-equipment cues",
            "movement path cues",
            "visual IDs",
            "VG-01",
            "VG-10",
            "Unified instance diagram",
            "Action path cue",
            "Beginner cue",
            "Equipment markers",
            "instance diagram cue",
            "common movements",
            "Smith machine",
            "史密斯机",
            "Cable station",
            "绳索龙门架/滑轮器械",
            "Dumbbells",
            "哑铃",
            "Barbell",
            "杠铃",
            "Machine",
            "固定轨迹器械",
            "Bodyweight or open station",
            "自重/开放训练空间",
            "guided incline press path",
            "align bench under the fixed bar path",
            "example movement",
            "look-for cue",
            "Common movements",
            "Look for two rails and a fixed bar",
            "Selected Day Visual Map",
            "Today's Exercise Visual Map",
            "exercise thumbnail headers",
            "Adjustable bench",
            "可调训练凳",
            "Pull-up/Dip station",
            "引体向上/双杠训练站",
            "Resistance band",
            "弹力带",
            "Leg press or hack squat",
            "腿举/哈克深蹲器械",
            "Look for a flat or adjustable bench",
            "Look for an overhead bar, dip handles, or assist platform",
            "Look for a band anchored to a rack, door, or post",
            "Look for a sled platform, seat, and safety handles",
            "Map the visible setup to the Exercise Visual Guide",
            "closest VG visual guide ID",
            "quick visual cue, find-equipment cue, and movement path cue",
            "Exercise Substitution Coach",
            "primaryOption",
            "secondaryOptions",
            "same target muscle",
            "same movement pattern",
            "planned rep range",
            "fatigue cost",
            "load-adjustment cue",
            "visual guide ID",
            "Warm-up Ramp Plan",
            "warm-up ramp set checklist",
            "planned working load",
            "final ramp set",
            "first working set gate",
            "Do not count warm-up ramp sets as hard sets",
            "Training Closeout Coach",
            "closeout score",
            "missing set logs",
            "form/equipment photo evidence",
            "post-workout nutrition",
            "Health Connect sync",
            "AI review readiness",
            "waistCm",
            "chestCm",
            "shoulderCm",
            "hipCm",
            "leftArmCm",
            "rightArmCm",
            "leftThighCm",
            "rightThighCm",
            "neckCm",
            "shoulder-to-waist ratio",
            "arm symmetry",
            "thigh symmetry",
        ]
        combined = f"{skill_library}\n{app_library}\n{visual_analysis}\n{app_visual_analysis}\n{nutrition_body_composition}\n{app_nutrition_body_composition}\n{session_execution}\n{app_session_execution}"
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, combined)


if __name__ == "__main__":
    unittest.main()
