import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "android-app"


class AndroidAppStructureTest(unittest.TestCase):
    def test_android_project_files_exist(self) -> None:
        required = [
            "README.md",
            "settings.gradle.kts",
            "build.gradle.kts",
            "gradle.properties",
            "app/build.gradle.kts",
            "app/src/main/AndroidManifest.xml",
            "app/src/main/java/com/iwanttobeanifbbpro/app/MainActivity.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/SkillPromptBuilder.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/SkillAssetRepository.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/ProgressionAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseHistoryAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/DailyExecutionAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/AiIntegratedDecisionAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/AiRestPrescriptionAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/MealAssemblyAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/SessionQualityAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/TrainingCloseoutAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/AiReviewActionAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/NextSetAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/WarmUpRampAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseSubstitutionAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/TomorrowCoachAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/WeeklyCheckInAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/BodyCompositionAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/ConditioningHydrationAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/PhysiqueMeasurementAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseVisualGuide.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/RecoveryAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/TrainingReadinessAdvisor.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/network/OpenAiResponsesClient.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/data/DailyLog.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/data/DailyLogStore.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/data/AiReviewStore.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/data/AthleteProfile.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/data/TrainingPlan.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/data/TrainingPlanStore.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/core/DailySummaryBuilder.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/health/HealthSnapshot.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/health/HealthConnectRepository.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/ui/AppTheme.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/ui/CoachViewModel.kt",
            "app/src/main/java/com/iwanttobeanifbbpro/app/ui/IfbbProCoachApp.kt",
        ]
        for relative in required:
            with self.subTest(relative=relative):
                self.assertTrue((APP / relative).exists(), relative)

    def test_app_embeds_skill_assets(self) -> None:
        asset_root = APP / "app/src/main/assets/skill"
        required_assets = [
            "SKILL.md",
            "references/evidence-map.md",
            "references/visual-analysis-and-food-estimation.md",
            "references/training-programming.md",
            "references/nutrition-body-composition.md",
            "references/session-execution-and-volume.md",
            "references/model-adaptation.md",
        ]
        for relative in required_assets:
            with self.subTest(relative=relative):
                self.assertTrue((asset_root / relative).exists(), relative)

    def test_api_client_supports_configurable_multimodal_responses_api(self) -> None:
        client = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/network/OpenAiResponsesClient.kt").read_text(
            encoding="utf-8"
        )
        expected_terms = [
            "/responses",
            "instructions",
            "input_image",
            "image_url",
            "promptLine(index",
            "data:",
            "output_text",
            "baseUrl",
            "apiKey",
            "model",
        ]
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, client)
        self.assertNotIn("sk-", client)

    def test_prompt_builder_exposes_skill_modes_and_linked_analysis(self) -> None:
        prompt = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/SkillPromptBuilder.kt").read_text(
            encoding="utf-8"
        )
        expected_terms = [
            "NEW_PLAN",
            "CHECK_IN",
            "TRAINING_VISUAL",
            "FOOD_VISUAL",
            "LINKED_TRAINING_NUTRITION",
            "evidence-map.md",
            "visual-analysis-and-food-estimation.md",
            "session-execution-and-volume.md",
            "nutrition-body-composition.md",
            "Exercise Substitution Coach",
            "Photo Evidence metadata",
            "exercise form frame",
            "physique progress photo",
            "same target muscle",
            "same movement pattern",
            "fatigue cost",
        ]
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, prompt)

    def test_daily_app_model_supports_training_nutrition_metrics_and_ai_review(self) -> None:
        model = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/DailyLog.kt").read_text(
            encoding="utf-8"
        )
        store = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/DailyLogStore.kt").read_text(
            encoding="utf-8"
        )
        plan_model = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/TrainingPlan.kt").read_text(
            encoding="utf-8"
        )
        log_model = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/DailyLog.kt").read_text(
            encoding="utf-8"
        )
        plan_store = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/TrainingPlanStore.kt").read_text(
            encoding="utf-8"
        )
        summary = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/DailySummaryBuilder.kt").read_text(
            encoding="utf-8"
        )
        ai_review_store = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/AiReviewStore.kt").read_text(
            encoding="utf-8"
        )
        athlete_profile = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/AthleteProfile.kt").read_text(
            encoding="utf-8"
        )
        expected_terms = [
            "AthleteProfile",
            "AthleteProfileStore",
            "athlete_profile",
            "primaryGoal",
            "currentPhase",
            "trainingExperience",
            "targetBodyFatPercent",
            "weeklyTrainingDays",
            "weakPoints",
            "constraints",
            "TrainingSession",
            "Daily Execution Plan",
            "DailyExecutionPlan",
            "DailyExecutionRoute",
            "dailyExecutionPlan",
            "AI Integrated Decision Matrix",
            "AiIntegratedDecisionMatrix",
            "aiIntegratedDecisionMatrix",
            "AI Plan Adjustment Proposal",
            "AiPlanAdjustmentProposal",
            "aiPlanAdjustmentProposal",
            "AI Rest Prescription",
            "AiRestPrescription",
            "aiRestPrescription",
            "aiRestPrescriptionForSet",
            "withAiMatchedRestTargets",
            "restSeconds auto update",
            "after AI review",
            "recommended rest",
            "auto-adjust rule",
            "next-session carryover",
            "recommended template",
            "split action",
            "volume action",
            "nutrition guardrail",
            "recovery guardrail",
            "Apply AI split template",
            "training effect",
            "Split decision",
            "3-day / 4-day / 5-day split decision",
            "data confidence",
            "all data linked",
            "do not change split until",
            "priorityFocus",
            "primaryActionLabel",
            "primaryActionRoute",
            "trainingDecision",
            "nutritionDecision",
            "recoveryDecision",
            "dataQualityGate",
            "aiReviewGate",
            "planAdjustmentSignal",
            "nextBestAction",
            "Primary action",
            "Data quality gate",
            "AI review gate",
            "Plan adjustment signal",
            "ExerciseEntry",
            "SetEntry",
            "WeeklyTrainingPlan",
            "TrainingDay",
            "PlannedExercise",
            "TrainingPlanTemplate",
            "trainingPlanTemplates",
            "Beginner Full Body",
            "4-Day Hypertrophy",
            "5-Day Physique Priority",
            "Beginner Full Body Foundation",
            "4-Day Hypertrophy Builder",
            "5-Day Physique Priority",
            "fillWeek",
            "planned(",
            "TrainingPlanStore",
            "readPlan",
            "savePlan",
            "toExerciseEntry",
            "MealEntry",
            "PhotoEvidenceType",
            "PhotoEvidenceEntry",
            "photoEvidence",
            "Food or label photo",
            "Exercise form frame",
            "Equipment photo",
            "Physique progress photo",
            "Menu or nutrition label",
            "Daily photo evidence",
            "MealTemplate",
            "mealTemplates",
            "toMealEntry",
            "Lean Protein Bowl",
            "Pre-Workout Carbs",
            "Low-Fat Protein Fix",
            "Salmon Potato Plate",
            "Fiber + Micronutrient Add",
            "DailyMetrics",
            "DailyTargets",
            "DailyConditioning",
            "conditioning",
            "stepGoal",
            "cardioMinutes",
            "cardioType",
            "cardioIntensity",
            "waterLiters",
            "sodiumMg",
            "caffeineMg",
            "alcoholServings",
            "digestion",
            "AiReviewEntry",
            "AiReviewStore",
            "readReviews",
            "saveReview",
            "ai_review_history",
            "setEntries",
            "completedHardSets",
            "trainingVolumeKg",
            "restSeconds",
            "calories",
            "protein",
            "carbs",
            "fat",
            "bodyWeightKg",
            "bodyFatPercent",
            "leanBodyMassKg",
            "waistCm",
            "chestCm",
            "shoulderCm",
            "hipCm",
            "leftArmCm",
            "rightArmCm",
            "leftThighCm",
            "rightThighCm",
            "neckCm",
            "sleepHours",
            "restingHeartRateBpm",
            "totalCaloriesBurnedKcal",
            "healthDataSource",
            "healthSyncedAt",
            "readLog",
            "saveLog",
            "readRecentLogs",
            "log_date_index",
            "log_",
            "buildAiReviewContext",
            "daily training",
            "daily nutrition",
            "AI review",
            "Athlete profile and goal",
            "Interpret today's data through the athlete profile",
            "set-level performance",
            "rest time",
            "Current weekly training plan",
            "Template context",
            "Health Connect-derived data",
            "Recent trend window",
            "Weight change in window",
            "Daily trend rows",
            "Nutrition pacing",
            "Meal template context",
            "adherence",
            "Next meal focus",
            "Next Meal Builder",
            "NextMealBuilderSummary",
            "nextMealBuilderSummary",
            "Meal Assembly Guide",
            "MealAssemblyGuide",
            "mealAssemblyGuide",
            "promptLine",
            "Plate structure",
            "Protein anchor",
            "Carb anchor",
            "Fat control",
            "Fiber/micros",
            "Shopping cue",
            "Prep cue",
            "Photo/logging cue",
            "Avoid cue",
            "Macro target",
            "Timing cue",
            "Portion cue",
            "Photo/label cue",
            "Body composition guidance",
            "BodyCompositionGuidance",
            "bodyCompositionGuidance",
            "calorie adjustment",
            "target calories",
            "phaseGoal",
            "Physique Measurement Summary",
            "PhysiqueMeasurementSummary",
            "physiqueMeasurementSummary",
            "shoulder-to-waist ratio",
            "arm difference",
            "thigh difference",
            "Proportion cue",
            "Symmetry cue",
            "Tracking cue",
            "waist change",
            "chest change",
            "shoulder change",
            "hip change",
            "Recovery guidance",
            "RecoveryGuidance",
            "recoveryGuidance",
            "Conditioning & Hydration",
            "ConditioningHydrationGuidance",
            "conditioningHydrationGuidance",
            "step goal progress",
            "cardio status",
            "hydration status",
            "sodium cue",
            "caffeine cue",
            "weight fluctuation cue",
            "scale-weight noise",
            "NEAT behind",
            "Hydration gap",
            "Stimulant pressure",
            "water, sodium, caffeine, cardio, steps",
            "recommended training action",
            "recommendedTrainingAction",
            "readiness score",
            "readinessScore",
            "training pressure",
            "trainingPressure",
            "Controlled push",
            "Hold training stress",
            "Reduce volume",
            "Deload check",
            "Training Readiness Builder",
            "TrainingReadinessBuilder",
            "trainingReadinessBuilder",
            "Warm-up Ramp Plan",
            "WarmUpRampPlan",
            "WarmUpRampSet",
            "warmUpRampPlan",
            "ramp set checklist",
            "planned load percentage",
            "final ramp set quality",
            "first working set gate",
            "working-load gate",
            "Next Set Coach",
            "NextSetCoach",
            "nextSetCoach",
            "currentExerciseName",
            "current exercise",
            "next set target",
            "load cue",
            "reps cue",
            "RIR cue",
            "rest cue",
            "stop cue",
            "after-set logging cue",
            "Load cue",
            "Reps cue",
            "Rest cue",
            "Stop cue",
            "After-set logging cue",
            "Tomorrow Coach Brief",
            "TomorrowCoachBrief",
            "tomorrowCoachBrief",
            "tomorrowDate",
            "planDayName",
            "planFocus",
            "trainingAction",
            "nutritionAction",
            "recoveryAction",
            "trackingAction",
            "readinessGate",
            "tomorrow training focus",
            "tomorrow nutrition target",
            "tomorrow recovery gate",
            "tomorrow tracking action",
            "promptLine",
            "Weekly Check-in",
            "WeeklyCheckInSummary",
            "weeklyCheckInSummary",
            "trainingCompletionPercent",
            "planAdjustment",
            "nutritionAdjustment",
            "weakPointFocus",
            "dataQualityGate",
            "nextWeekAction",
            "Use Weekly Check-in before changing plan-wide volume or calorie targets",
            "Session Quality Dashboard",
            "SessionQualityDashboard",
            "sessionQualityDashboard",
            "Training Closeout Coach",
            "TrainingCloseoutCoach",
            "TrainingCloseoutTask",
            "trainingCloseoutCoach",
            "AI Review Action Queue",
            "AiReviewActionQueue",
            "AiReviewActionItem",
            "AiReviewActionCategory",
            "aiReviewActionQueue",
            "sourceLabel",
            "confidenceLabel",
            "primaryAction",
            "actionLabel",
            "Review saved guidance",
            "Run daily review",
            "training action",
            "nutrition action",
            "recovery action",
            "tracking action",
            "closeoutScore",
            "missingLogCount",
            "photoCue",
            "nutritionCue",
            "metricsCue",
            "sessionNoteCue",
            "AI review readiness",
            "missing set logs",
            "post-workout nutrition",
            "MuscleVolumeShare",
            "completionRatePercent",
            "loggedSetRatePercent",
            "averageRir",
            "painFlagCount",
            "techniqueFlagCount",
            "topMuscleVolumes",
            "qualityCue",
            "capacityCue",
            "riskCue",
            "Muscle volume",
            "Quality cue",
            "Capacity cue",
            "Risk cue",
            "Warm-up cue",
            "warmUpCue",
            "Ramp-up cue",
            "rampUpCue",
            "First working set",
            "firstWorkingSetCue",
            "Volume adjustment",
            "volumeAdjustmentCue",
            "Stop rule",
            "stopRule",
            "AI review focus",
            "aiReviewFocus",
            "Exercise visual guide",
            "setup steps",
            "common mistakes",
            "attach equipment photo",
            "find this equipment",
            "Unified Exercise Visual Atlas",
            "Exercise Visual Legend",
            "统一动作图例",
            "visualPromptLine",
            "visual IDs",
            "equipment/action categories",
            "Chinese equipment labels",
            "unified instance diagrams",
            "three-step recognition",
            "ExerciseVisualAtlas",
            "exerciseVisualAtlas",
            "recognitionSteps",
            "recognitionFlow",
            "atlasLine",
            "action path cues",
            "quick visual cues",
            "find-equipment cues",
            "movement path cues",
            "beginner recognition cues",
            "equipment markers",
            "instance diagram cues",
            "common movements",
            "ExerciseVisualSpec",
            "ExerciseVisualType",
            "exerciseVisualLibrarySpecs",
            "visualId",
            "figureTitle",
            "actionPathCue",
            "quickVisualCue",
            "findEquipmentCue",
            "movementPathCue",
            "beginnerCue",
            "equipmentMarkers",
            "VG-01",
            "VG-10",
            "equipmentZh",
            "instanceCue",
            "commonMovements",
            "Adjustable bench",
            "Pull-up/Dip station",
            "Resistance band",
            "Leg press or hack squat",
            "Progression cue",
            "Use each Progression Cue",
            "progressionCue",
            "Exercise Substitution Coach",
            "ExerciseSubstitutionGuide",
            "ExerciseSubstitutionOption",
            "exerciseSubstitutionGuide",
            "equipment unavailable",
            "primaryOption",
            "secondaryOptions",
            "same target muscle",
            "same movement pattern",
            "preserve rep range",
            "fatigue cost",
            "keepIntentCue",
            "loadAdjustmentCue",
            "visual guide ID",
            "Exercise history",
            "Compare Exercise History",
            "exerciseHistorySummary",
            "previous volume",
            "current volume",
            "best load",
            "best reps",
            "average RIR",
        ]
        progression = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ProgressionAdvisor.kt").read_text(
            encoding="utf-8"
        )
        history = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseHistoryAdvisor.kt").read_text(
            encoding="utf-8"
        )
        body_composition = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/BodyCompositionAdvisor.kt"
        ).read_text(encoding="utf-8")
        physique_measurement = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/PhysiqueMeasurementAdvisor.kt"
        ).read_text(encoding="utf-8")
        daily_execution = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/DailyExecutionAdvisor.kt"
        ).read_text(encoding="utf-8")
        ai_integrated = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/AiIntegratedDecisionAdvisor.kt"
        ).read_text(encoding="utf-8")
        ai_rest = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/AiRestPrescriptionAdvisor.kt"
        ).read_text(encoding="utf-8")
        meal_assembly = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/MealAssemblyAdvisor.kt"
        ).read_text(encoding="utf-8")
        session_quality = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/SessionQualityAdvisor.kt"
        ).read_text(encoding="utf-8")
        training_closeout = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/TrainingCloseoutAdvisor.kt"
        ).read_text(encoding="utf-8")
        ai_review_action = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/AiReviewActionAdvisor.kt"
        ).read_text(encoding="utf-8")
        recovery = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/RecoveryAdvisor.kt").read_text(
            encoding="utf-8"
        )
        conditioning = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ConditioningHydrationAdvisor.kt"
        ).read_text(encoding="utf-8")
        training_readiness = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/TrainingReadinessAdvisor.kt"
        ).read_text(encoding="utf-8")
        next_set = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/NextSetAdvisor.kt"
        ).read_text(encoding="utf-8")
        warm_ramp = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/WarmUpRampAdvisor.kt"
        ).read_text(encoding="utf-8")
        tomorrow = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/TomorrowCoachAdvisor.kt"
        ).read_text(encoding="utf-8")
        weekly_checkin = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/WeeklyCheckInAdvisor.kt"
        ).read_text(encoding="utf-8")
        substitution = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseSubstitutionAdvisor.kt"
        ).read_text(encoding="utf-8")
        visual = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseVisualGuide.kt").read_text(
            encoding="utf-8"
        )
        combined = f"{model}\n{store}\n{ai_review_store}\n{athlete_profile}\n{plan_model}\n{plan_store}\n{summary}\n{progression}\n{history}\n{body_composition}\n{physique_measurement}\n{daily_execution}\n{ai_integrated}\n{ai_rest}\n{meal_assembly}\n{session_quality}\n{training_closeout}\n{ai_review_action}\n{recovery}\n{conditioning}\n{training_readiness}\n{next_set}\n{warm_ramp}\n{tomorrow}\n{weekly_checkin}\n{substitution}\n{visual}"
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, combined)

    def test_ui_exposes_daily_workflows(self) -> None:
        ui = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/ui/IfbbProCoachApp.kt").read_text(
            encoding="utf-8"
        )
        view_model = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/ui/CoachViewModel.kt").read_text(
            encoding="utf-8"
        )
        plan_model = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/TrainingPlan.kt").read_text(
            encoding="utf-8"
        )
        log_model = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/data/DailyLog.kt").read_text(
            encoding="utf-8"
        )
        app_tab_match = re.search(r"enum class AppTab[^{]*\{(?P<body>.*?)\n\}", view_model, re.DOTALL)
        self.assertIsNotNone(app_tab_match, "AppTab enum should be declared in CoachViewModel.kt")
        app_tabs = re.findall(r"^\s*([A-Z_]+)\(", app_tab_match.group("body"), re.MULTILINE)
        self.assertEqual(["TRAINING", "NUTRITION", "METRICS", "AI_COACH"], app_tabs)
        self.assertIn("AppTab.entries.forEach", ui)
        self.assertIn("Icon(", ui)
        self.assertIn("ImageVector", ui)
        self.assertNotIn("icon = { Text(tab.navIcon()) }", ui)
        expected_terms = [
            "Training",
            "Nutrition",
            "Metrics",
            "AI Coach",
            "AppLanguage",
            "appLanguage",
            "updateLanguage",
            "loadLanguage",
            "saveLanguage",
            "localizedTitle",
            "GlobalNextActionStrip",
            "TODAY NEXT",
            "One tap daily start",
            "QuickSetupGateCard",
            "3-tap setup gate",
            "Goal / Days / Equipment",
            "Recommended split from setup",
            "AI uses setup: goal, training days, equipment, phase, constraints",
            "目标 / 天数 / 器械",
            "Today Flow Coach",
            "TodayFlowCoachState",
            "todayFlowCoachState",
            "showTodayDetails",
            "TrainingModeSwitch",
            "Today workout",
            "Plan library",
            "NEXT BEST ACTION",
            "Show detail layers",
            "Hide detail layers",
            "Meal Flow Coach",
            "MealFlowCoachCard",
            "NutritionAutopilotCard",
            "NUTRITION AUTOPILOT",
            "Nutrition Autopilot",
            "Eat -> Capture -> Confirm -> Review",
            "Current meal target",
            "Macro gaps",
            "Photo confidence",
            "Next nutrition action",
            "饮食自动教练",
            "showNutritionDetails",
            "Show nutrition details",
            "Hide nutrition details",
            "NEXT MEAL ACTION",
            "Prefill next meal",
            "AI nutrition review",
            "Nutrition detail layers hidden",
            "Metrics Flow Coach",
            "MetricsFlowCoachCard",
            "MetricsAutopilotCard",
            "METRICS AUTOPILOT",
            "Metrics Autopilot",
            "Sync -> Trend -> Photo -> Review",
            "Trend confidence",
            "Sleep and recovery",
            "Health permission",
            "Next metrics action",
            "身体数据自动教练",
            "showMetricsDetails",
            "Show metrics details",
            "Hide metrics details",
            "NEXT METRICS ACTION",
            "Metrics detail layers hidden",
            "Connect health data",
            "Sync today's metrics",
            "Progress photo linked to measurements",
            "AI Review Flow Coach",
            "AiReviewFlowCoachCard",
            "showAiDetails",
            "showAiDailyOverview",
            "AI Daily Overview",
            "Show daily overview",
            "Hide daily overview",
            "default AI page stays focused",
            "Show AI details",
            "Hide AI details",
            "NEXT AI REVIEW ACTION",
            "AI detail layers hidden",
            "DailyAutopilotCard",
            "DAILY AUTOPILOT",
            "Daily Autopilot",
            "Follow this order today",
            "Train -> Eat -> Sync -> Review",
            "Current next step",
            "Today's evidence gaps",
            "Autopilot action",
            "One screen daily loop",
            "每日自动教练",
            "训练 -> 饮食 -> 同步 -> 复盘",
            "ReviewReadinessChecklistCard",
            "REVIEW READINESS",
            "Training evidence",
            "Nutrition evidence",
            "Metrics evidence",
            "Photo/API context",
            "Fix missing evidence before AI changes training or food",
            "复盘准备度",
            "AiChangeReceiptCard",
            "AI CHANGE RECEIPT",
            "What changed for next session",
            "Training changes",
            "Rest changes",
            "Nutrition changes",
            "Recovery guardrail",
            "Tracking lock",
            "Applied to next workout",
            "Held until more evidence",
            "AI 变更回执",
            "Daily review evidence bundle",
            "Training, food, metrics, photos, trends",
            "Start Here",
            "从这里开始",
            "DailyStartStep",
            "dailyStartSteps",
            "StartHereCoachCard",
            "StartHereStepRow",
            "EN",
            "中文",
            "AiSettings",
            "isConfigured",
            "AiSetupStatus",
            "aiSetupStatus",
            "AiSetupStatusCard",
            "AI Setup & Review Readiness",
            "Set API first",
            "Missing setup",
            "AI review ready",
            "Photo context linked",
            "AI setup is not ready",
            "addExercise",
            "addMeal",
            "addMealTemplate",
            "updateMetrics",
            "updateTargets",
            "updateConditioning",
            "runDailyReview",
            "hard sets",
            "meal photo",
            "MealEstimateReceiptCard",
            "AI MEAL ESTIMATE",
            "Meal estimate receipt",
            "Estimated macros",
            "Confidence",
            "Logged to today",
            "Remaining after this meal",
            "Confirm portions, oil, sauce, and labels",
            "餐食估算回执",
            "PhotoEvidenceCard",
            "PhotoEvidenceType",
            "Photo Evidence",
            "Photo purpose",
            "Form photo",
            "Equipment photo",
            "Progress photo",
            "Food or label photo",
            "Exercise form frame",
            "Physique progress photo",
            "addPreparedImages",
            "preparePhotoEvidence",
            "pendingPhotoType",
            "pendingPhotoNote",
            "Rest timer",
            "AI Rest Prescription",
            "AiRestPrescriptionCard",
            "restSeconds auto update",
            "after AI review",
            "AI matched rest",
            "Complete",
            "AI Data Map",
            "Set load",
            "Actual reps",
            "Weekly Plan",
            "Plan Flow Coach",
            "PlanFlowCoachCard",
            "AiPlanAdjustmentProposalCard",
            "AI Plan Adjustment Proposal",
            "Apply AI split template",
            "template proposal from linked evidence",
            "showPlanDetails",
            "Show plan details",
            "Hide plan details",
            "Plan detail layers hidden",
            "Use recommended template",
            "Template -> weekly plan -> Apply today",
            "Plan Templates",
            "PlanTemplateLibrary",
            "PlanTemplateCard",
            "applyTrainingPlanTemplate",
            "trainingPlanTemplates",
            "Beginner Full Body",
            "4-Day Hypertrophy",
            "5-Day Physique Priority",
            "Use",
            "Current",
            "Athlete Profile",
            "Primary physique goal",
            "Weak points or physique priorities",
            "updateAthleteProfile",
            "athleteProfile",
            "Apply today",
            "addPlannedExercise",
            "applyPlanDayToToday",
            "Health Connect",
            "Connect health data",
            "Sync today",
            "HealthSyncReceiptCard",
            "HEALTH SYNC RECEIPT",
            "Health sync receipt",
            "Imported today",
            "Missing signals",
            "AI uses sleep, weight, steps, resting HR, and calorie burn",
            "Auto refresh on app open",
            "Manual fallback still works",
            "健康同步回执",
            "Body fat",
            "Resting HR",
            "healthPermissions",
            "syncHealthData",
            "IfbbProTheme",
            "AppleInspiredLightColors",
            "Scaffold",
            "NavigationBar",
            "NavigationBarItem",
            "Command Center",
            "Daily Execution Plan",
            "DailyExecutionPlan",
            "DailyExecutionPlanCard",
            "DailyExecutionRoute",
            "dailyExecutionPlan",
            "Priority",
            "Priority focus",
            "Primary action",
            "Data quality gate",
            "AI review gate",
            "Plan adjustment signal",
            "Daily Coach Checklist",
            "DailyCoachTask",
            "dailyCoachTasks",
            "DailyCoachChecklistCard",
            "plan, train, eat, sync",
            "Plan prepared",
            "Training executed",
            "Food logged",
            "Metrics synced",
            "AI review locked",
            "Run review",
            "View review",
            "Beginner Friendly Flow",
            "Readiness",
            "Today Snapshot",
            "dailyReadiness",
            "recentLogs",
            "7-Day Trend",
            "TrendOverviewCard",
            "reviewHistory",
            "Saved AI Reviews",
            "Latest AI guidance",
            "ReviewHistoryCard",
            "AI Review Action Queue",
            "AiReviewActionQueueCard",
            "AiReviewActionRow",
            "performAiReviewAction",
            "sourceLabel",
            "confidenceLabel",
            "primaryAction",
            "actionLabel",
            "Review saved guidance",
            "Run daily review",
            "training action",
            "nutrition action",
            "recovery action",
            "tracking action",
            "plan action",
            "Unified health permission",
            "Auto refresh after permission",
            "Body, sleep, steps, HR, calories",
            "Manual fallback",
            "Body Trend Chart",
            "7-day trend graph",
            "Today Visual Primer",
            "TodayExerciseVisualPrimerCard",
            "ExerciseVisualGuide",
            "ExerciseVisualGuideLibrary",
            "ExerciseVisualGuideSample",
            "ExerciseVisualLegendGrid",
            "ExerciseVisualLegendTile",
            "ExerciseVisualMap",
            "ExerciseVisualMapItem",
            "ExerciseVisualMapRow",
            "ExerciseVisualHeader",
            "ExerciseVisualType",
            "drawExerciseVisual",
            "Exercise visual guide",
            "Selected Day Visual Map",
            "Today's Exercise Visual Map",
            "thumbnail",
            "统一动作图例",
            "Visual guide ID",
            "Unified instance diagram",
            "Unified Exercise Visual Atlas",
            "Three-step recognition",
            "Simplified instance diagram",
            "Find real equipment",
            "Movement path matching",
            "Action path cue",
            "Quick visual cue",
            "Find equipment cue",
            "Movement path cue",
            "Beginner recognition cue",
            "Equipment markers",
            "Exercise Visual Library",
            "ExerciseVisualAtlasOverview",
            "ExerciseVisualRecognitionPreview",
            "Live equipment/action preview",
            "Chinese equipment labels",
            "visualId",
            "figureTitle",
            "actionPathCue",
            "quickVisualCue",
            "findEquipmentCue",
            "movementPathCue",
            "beginnerCue",
            "equipmentMarkers",
            "VG-01",
            "VG-10",
            "Instance diagram cue",
            "Common movement examples",
            "Equipment photo recognition",
            "Exercise name -> visual category",
            "simple equipment/action instance diagrams",
            "equipment/action thumbnails",
            "equipmentZh",
            "instanceCue",
            "commonMovements",
            "史密斯机",
            "哑铃",
            "Smith machine",
            "Cable station",
            "Dumbbells",
            "Barbell",
            "Machine",
            "Bodyweight or open station",
            "Adjustable bench",
            "Pull-up/Dip station",
            "Resistance band",
            "Leg press or hack squat",
            "Example: ${spec.example}",
            "Look for two rails and a fixed bar",
            "Look for a cable, pulley, and handle",
            "Look for a flat or adjustable bench",
            "Look for an overhead bar, dip handles, or assist platform",
            "Look for a band anchored to a rack, door, or post",
            "Look for a sled platform, seat, and safety handles",
            "equipment/action instance diagrams",
            "Chinese equipment labels",
            "Instance diagram cue",
            "Common movement examples",
            "Dumbbell Row",
            "Barbell Squat",
            "Machine Chest Press",
            "Incline Dumbbell Press",
            "Band Face Pull",
            "Leg Press",
            "NutritionPacing",
            "Nutrition Pacing",
            "NextMealBuilder",
            "Next Meal Builder",
            "Meal Flow Coach",
            "MealFlowCoachCard",
            "showNutritionDetails",
            "Prefill next meal",
            "AI nutrition review",
            "Food photo nutrition estimate",
            "NextMealBuilderCard",
            "nextMealBuilder",
            "Meal Logging Coach",
            "MealLoggingCoachCard",
            "recommendedMealTemplate",
            "Coach prefill",
            "Prefill target",
            "Add template",
            "Food/menu/label photo for AI nutrition estimate",
            "AI link: daily review uses logged macros",
            "MealAssemblyGuide",
            "Meal Assembly Guide",
            "MealAssemblyGuideCard",
            "mealAssemblyGuide",
            "Plate structure",
            "Protein anchor",
            "Carb anchor",
            "Fat control",
            "Fiber/micros",
            "Shopping cue",
            "Prep cue",
            "Photo/logging cue",
            "Next meal macro targets",
            "Meal timing cue",
            "Portion uncertainty cue",
            "MealTemplate",
            "Meal Templates",
            "MealTemplateLibrary",
            "MealTemplateCard",
            "mealTemplates",
            "Lean Protein Bowl",
            "Pre-Workout Carbs",
            "Low-Fat Protein Fix",
            "Salmon Potato Plate",
            "Fiber + Micronutrient Add",
            "BodyCompositionGuidance",
            "Body Composition Guidance",
            "BodyCompositionCard",
            "bodyCompositionGuidance",
            "PhysiqueMeasurementSummary",
            "Physique Measurement Summary",
            "PhysiqueMeasurementSummaryCard",
            "physiqueMeasurementSummary",
            "Metrics Flow Coach",
            "MetricsFlowCoachCard",
            "showMetricsDetails",
            "Metrics detail layers",
            "Sync today's metrics",
            "Health Connect or manual fallback",
            "Physique Measurements",
            "Chest cm",
            "Shoulder cm",
            "Hip cm",
            "Left arm cm",
            "Right arm cm",
            "Left thigh cm",
            "Right thigh cm",
            "Neck cm",
            "shoulder-to-waist ratio",
            "arm symmetry",
            "thigh symmetry",
            "V-taper direction",
            "Small calorie increase",
            "Small calorie decrease",
            "Hold targets",
            "Need trend data",
            "Kcal adjust",
            "Weight trend",
            "RecoveryGuidance",
            "Recovery Guidance",
            "RecoveryGuidanceCard",
            "recoveryGuidance",
            "ConditioningHydrationGuidance",
            "Conditioning & Hydration",
            "ConditioningHydrationCard",
            "conditioningHydrationGuidance",
            "DailyConditioning",
            "Step goal",
            "Cardio min",
            "Cardio type",
            "Intensity",
            "Water L",
            "Sodium mg",
            "Caffeine mg",
            "Alcohol",
            "Digestion, bloating, high-salt meal, cramps, pump",
            "scale-weight noise",
            "Training action",
            "Sleep signal",
            "HR signal",
            "Controlled push",
            "Hold training stress",
            "Reduce volume",
            "Deload check",
            "WorkoutFlowCoachCard",
            "Workout Flow Coach",
            "TodayReadinessGateCard",
            "Today Readiness Gate",
            "Push / Hold / Reduce / Recover",
            "Training decision",
            "Fuel gate",
            "Sleep + HR + soreness + RIR",
            "today readiness gate",
            "push hold reduce recover",
            "Professional detail layers",
            "showProfessionalDetails",
            "Show professional details",
            "Hide professional details",
            "TrainingReadinessBuilder",
            "TrainingReadinessBuilderCard",
            "trainingReadinessBuilder",
            "Training Readiness Builder",
            "WarmUpRampPlan",
            "WarmUpRampSet",
            "WarmUpRampPlanCard",
            "warmUpRampPlan",
            "Warm-up Ramp Plan",
            "Ramp set checklist",
            "planned load percentage",
            "final ramp set quality",
            "first working set gate",
            "NextSetCoach",
            "NextSetCoachCard",
            "nextSetCoach",
            "Next Set Coach",
            "Current exercise",
            "Next set target",
            "Load cue",
            "Reps/RIR",
            "Rest cue",
            "Execution cue",
            "Stop cue",
            "After-set logging cue",
            "TomorrowCoachBrief",
            "TomorrowCoachBriefCard",
            "NextDayHandoffCard",
            "tomorrowCoachBrief",
            "Tomorrow Coach Brief",
            "Next Day Handoff",
            "Wake up and follow this",
            "tomorrow handoff action",
            "one-tap next day plan",
            "AI links training, food, recovery, and tracking into tomorrow",
            "Tomorrow training focus",
            "Tomorrow nutrition target",
            "Tomorrow recovery gate",
            "Tomorrow tracking action",
            "Plan tomorrow",
            "Food targets",
            "Readiness gate",
            "WeeklyCheckInSummary",
            "WeeklyCheckInCard",
            "weeklyCheckInSummary",
            "Weekly Check-in",
            "Training completion",
            "Plan adjustment",
            "Nutrition adjustment",
            "Weak point",
            "Next week action",
            "SessionQualityDashboard",
            "SessionQualityDashboardCard",
            "sessionQualityDashboard",
            "Session Quality Dashboard",
            "TrainingCloseoutCoach",
            "TrainingCloseoutTask",
            "TrainingCloseoutCoachCard",
            "trainingCloseoutCoach",
            "Training Closeout Coach",
            "Closeout",
            "Missing logs",
            "Finish sets",
            "Complete set logs",
            "Add form evidence",
            "Log post-workout food",
            "Sync recovery metrics",
            "AI review readiness",
            "photo evidence cue",
            "post-workout nutrition cue",
            "metrics sync cue",
            "Completion rate",
            "Logged set rate",
            "Average RIR",
            "Muscle volume distribution",
            "Pain flags",
            "Technique flags",
            "qualityCue",
            "capacityCue",
            "riskCue",
            "Warm-up cue",
            "Ramp-up cue",
            "First working set",
            "Volume adjustment",
            "Stop rule",
            "Recovery gate",
            "warmUpCue",
            "rampUpCue",
            "firstWorkingSetCue",
            "volumeAdjustmentCue",
            "stopRule",
            "nextMealFocus",
            "Next meal focus",
            "formatRemaining",
            "$unit left",
            "over",
            "adherenceScore",
            "ProgressionCue",
            "Progression Cue",
            "ExerciseSubstitutionGuide",
            "ExerciseSubstitutionCard",
            "Exercise Substitution Coach",
            "exerciseSubstitutionGuide",
            "equipment unavailable",
            "trigger reason",
            "primaryOption",
            "secondaryOptions",
            "same target muscle",
            "same movement pattern",
            "preserve rep range",
            "fatigue cost",
            "keepIntentCue",
            "loadAdjustmentCue",
            "ExerciseHistorySummary",
            "ExerciseHistoryCard",
            "Exercise History",
            "exerciseHistorySummary",
            "First tracked session",
            "Volume up",
            "Volume down",
            "Load PR",
            "Rep PR",
            "Matched last time",
            "Last volume",
            "Today volume",
            "Best load",
            "Best reps",
            "Avg RIR",
            "Add reps first",
            "Add load next time",
            "Hold load",
            "Modify or hold",
            "Finish baseline",
            "hasPainSignal",
            "no pain",
        ]
        activity = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/MainActivity.kt").read_text(encoding="utf-8")
        theme = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/ui/AppTheme.kt").read_text(encoding="utf-8")
        progression = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ProgressionAdvisor.kt").read_text(
            encoding="utf-8"
        )
        history = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseHistoryAdvisor.kt").read_text(
            encoding="utf-8"
        )
        body_composition = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/BodyCompositionAdvisor.kt"
        ).read_text(encoding="utf-8")
        physique_measurement = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/PhysiqueMeasurementAdvisor.kt"
        ).read_text(encoding="utf-8")
        daily_execution = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/DailyExecutionAdvisor.kt"
        ).read_text(encoding="utf-8")
        meal_assembly = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/MealAssemblyAdvisor.kt"
        ).read_text(encoding="utf-8")
        session_quality = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/SessionQualityAdvisor.kt"
        ).read_text(encoding="utf-8")
        training_closeout = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/TrainingCloseoutAdvisor.kt"
        ).read_text(encoding="utf-8")
        ai_review_action = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/AiReviewActionAdvisor.kt"
        ).read_text(encoding="utf-8")
        recovery = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/RecoveryAdvisor.kt").read_text(
            encoding="utf-8"
        )
        conditioning = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ConditioningHydrationAdvisor.kt"
        ).read_text(encoding="utf-8")
        training_readiness = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/TrainingReadinessAdvisor.kt"
        ).read_text(encoding="utf-8")
        next_set = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/NextSetAdvisor.kt"
        ).read_text(encoding="utf-8")
        warm_ramp = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/WarmUpRampAdvisor.kt"
        ).read_text(encoding="utf-8")
        tomorrow = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/TomorrowCoachAdvisor.kt"
        ).read_text(encoding="utf-8")
        weekly_checkin = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/WeeklyCheckInAdvisor.kt"
        ).read_text(encoding="utf-8")
        substitution = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseSubstitutionAdvisor.kt"
        ).read_text(encoding="utf-8")
        visual = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/core/ExerciseVisualGuide.kt").read_text(
            encoding="utf-8"
        )
        combined = f"{ui}\n{view_model}\n{plan_model}\n{log_model}\n{activity}\n{theme}\n{progression}\n{history}\n{body_composition}\n{physique_measurement}\n{daily_execution}\n{meal_assembly}\n{session_quality}\n{training_closeout}\n{ai_review_action}\n{recovery}\n{conditioning}\n{training_readiness}\n{next_set}\n{warm_ramp}\n{tomorrow}\n{weekly_checkin}\n{substitution}\n{visual}"
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, combined)

    def test_four_main_sections_use_semantic_navigation_icons(self) -> None:
        gradle = (APP / "app/build.gradle.kts").read_text(encoding="utf-8")
        ui = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/ui/IfbbProCoachApp.kt").read_text(
            encoding="utf-8"
        )
        preview = (APP / "preview/index.html").read_text(encoding="utf-8")
        combined_android = f"{gradle}\n{ui}"
        expected_android_terms = [
            "material-icons-extended",
            "Icons.Filled.FitnessCenter",
            "Icons.Filled.Restaurant",
            "Icons.Filled.MonitorHeart",
            "Icons.Filled.AutoAwesome",
            "contentDescription = tab.localizedTitle(language)",
            "AppTab.NUTRITION -> language.t(\"Nutrition\", \"饮食\")",
            "AppTab.METRICS -> language.t(\"Metrics\", \"身体数据\")",
            "AppTab.AI_COACH -> language.t(\"AI\", \"AI\")",
        ]
        for term in expected_android_terms:
            with self.subTest(term=term):
                self.assertIn(term, combined_android)
        for placeholder in [
            'AppTab.TRAINING -> "T"',
            'AppTab.NUTRITION -> "N"',
            'AppTab.METRICS -> "M"',
            'AppTab.AI_COACH -> "AI"',
            "icon = { Text(tab.navIcon()) }",
        ]:
            with self.subTest(placeholder=placeholder):
                self.assertNotIn(placeholder, ui)

        self.assertEqual(4, len(re.findall(r'class="tab(?: active)?" type="button" data-tab=', preview)))
        expected_preview_terms = [
            'class="tab-icon"',
            'class="tab-label"',
            'data-tab="training"',
            'data-tab="nutrition"',
            'data-tab="metrics"',
            'data-tab="ai"',
            'data-aria-en="Training"',
            'data-aria-zh="训练"',
            'data-aria-zh="身体数据"',
            'setAttribute("aria-label"',
            'data-zh="身体数据"',
        ]
        for term in expected_preview_terms:
            with self.subTest(term=term):
                self.assertIn(term, preview)
        for placeholder in ["<span>T</span>", "<span>N</span>", "<span>M</span>", "<span>A</span>"]:
            with self.subTest(placeholder=placeholder):
                self.assertNotIn(placeholder, preview)
        self.assertNotIn('data-tab="today"', preview)
        self.assertNotIn('data-tab="plan"', preview)
        self.assertEqual(
            ["training", "nutrition", "metrics", "ai"],
            re.findall(r'<section class="panel(?: active)?" data-panel="([^"]+)"', preview),
        )
        self.assertIn('data-folded-panel="training"', preview)
        self.assertIn('data-folded-panel="ai"', preview)
        self.assertIn("mountFoldedPanels", preview)
        self.assertIn("target.appendChild(layer)", preview)
        self.assertNotIn('data-panel="training-plan"', preview)
        self.assertNotIn('data-panel="daily-overview"', preview)

    def test_next_day_handoff_is_visible_in_ai_flow_and_preview(self) -> None:
        ui = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/ui/IfbbProCoachApp.kt").read_text(
            encoding="utf-8"
        )
        preview = (APP / "preview/index.html").read_text(encoding="utf-8")
        expected_ui_terms = [
            "private fun NextDayHandoffCard(",
            'language.t("Next Day Handoff"',
            'language.t("Wake up and follow this"',
            "tomorrow handoff action",
            "one-tap next day plan",
            "AI links training, food, recovery, and tracking into tomorrow",
            "Tomorrow training focus",
            "Tomorrow nutrition target",
            "Tomorrow recovery gate",
            "Tomorrow tracking action",
            "NextDayHandoffCard(",
        ]
        for term in expected_ui_terms:
            with self.subTest(term=term):
                self.assertIn(term, ui)

        expected_preview_terms = [
            "Next Day Handoff",
            "Wake up and follow this",
            "tomorrow handoff action",
            "one-tap next day plan",
            "AI links training, food, recovery, and tracking into tomorrow",
            "Tomorrow training focus",
            "Tomorrow nutrition target",
            "Tomorrow recovery gate",
            "Tomorrow tracking action",
        ]
        for term in expected_preview_terms:
            with self.subTest(term=term):
                self.assertIn(term, preview)

    def test_android_compose_uses_shared_apple_glass_surfaces(self) -> None:
        theme = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/ui/AppTheme.kt").read_text(
            encoding="utf-8"
        )
        ui = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/ui/IfbbProCoachApp.kt").read_text(
            encoding="utf-8"
        )
        expected_theme_terms = [
            "IfbbProGlassSurface",
            "IfbbProGlassStrongSurface",
            "IfbbProGlassBorder",
            "GlassNavigationBarColor",
            ".copy(alpha = 0.78f)",
            ".copy(alpha = 0.92f)",
        ]
        for term in expected_theme_terms:
            with self.subTest(term=term):
                self.assertIn(term, theme)

        expected_ui_terms = [
            "NavigationBar(containerColor = GlassNavigationBarColor)",
            "CardDefaults.cardColors(containerColor = IfbbProGlassSurface)",
            "BorderStroke(1.dp, IfbbProGlassBorder)",
            "color = IfbbProGlassStrongSurface",
            "Apple glass surface",
        ]
        for term in expected_ui_terms:
            with self.subTest(term=term):
                self.assertIn(term, ui)

    def test_metrics_health_data_layer_uses_localized_labels(self) -> None:
        ui = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/ui/IfbbProCoachApp.kt").read_text(
            encoding="utf-8"
        )
        preview = (APP / "preview/index.html").read_text(encoding="utf-8")
        expected_terms = [
            "private fun ConditioningHydrationCard(",
            "language: AppLanguage",
            "private fun TrendOverviewCard(logs: List<DailyLog>, language: AppLanguage)",
            "private fun RecoveryGuidanceCard(guidance: RecoveryGuidance, subtitle: String, language: AppLanguage)",
            "private fun PhysiqueMeasurementSummaryCard(summary: PhysiqueMeasurementSummary, language: AppLanguage)",
            "HealthSnapshot.localizedMessage",
            'language.t("Health Connect", "健康数据连接")',
            'language.t("Connect health data", "连接健康数据")',
            'language.t("Sync today", "同步今天")',
            'language.t("Physique Photo Check-in", "体型照片打卡")',
            'language.t("Metrics", "身体数据")',
            'language.t("Body composition", "身体组成")',
            'language.t("Weight kg", "体重 kg")',
            'language.t("Body fat %", "体脂 %")',
            'language.t("Chest cm", "胸围 cm")',
            'language.t("Shoulder cm", "肩围 cm")',
            'language.t("Left arm cm", "左臂 cm")',
            'language.t("Right thigh cm", "右大腿 cm")',
            'language.t("Recovery inputs", "恢复输入")',
            'language.t("Daily reflection", "每日反思")',
            'language.t("7-Day Trend", "7 日趋势")',
            'language.t("Manual fallback", "手动补录")',
            "Unified health permission",
            "Auto refresh after permission",
            "Source apps stay behind the scenes",
            "Body Trend Chart",
            "TrendSparkline",
        ]
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, ui)

        forbidden_terms = [
            'Text("Connect health data")',
            'Text("Progress photo")',
            'label = { Text("Daily reflection") }',
            'title = "Health Connect"',
            'title = "Physique Photo Check-in"',
            'private fun TrendOverviewCard(logs: List<DailyLog>)',
            'private fun RecoveryGuidanceCard(guidance: RecoveryGuidance, subtitle: String)',
            'private fun PhysiqueMeasurementSummaryCard(summary: PhysiqueMeasurementSummary)',
        ]
        for term in forbidden_terms:
            with self.subTest(term=term):
                self.assertNotIn(term, ui)

        preview_terms = [
            'data-zh="健康数据连接"',
            'data-zh="连接健康数据"',
            'data-zh="同步今天"',
            'data-zh="恢复建议"',
            'data-zh="有氧、活动量与补水"',
            'data-zh="体型围度摘要"',
            'data-zh="体型照片打卡"',
            'data-zh="体型围度"',
            'data-zh="胸围 cm"',
            'data-zh="肩围 cm"',
            'data-zh="左臂 cm"',
            'data-zh="右大腿 cm"',
            'data-zh="恢复输入"',
            'data-zh="手动补录"',
        ]
        for term in preview_terms:
            with self.subTest(term=term):
                self.assertIn(term, preview)

    def test_nutrition_detail_layers_use_localized_copy(self) -> None:
        ui = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/ui/IfbbProCoachApp.kt").read_text(
            encoding="utf-8"
        )
        preview = (APP / "preview/index.html").read_text(encoding="utf-8")
        expected_ui_terms = [
            "private fun MealAssemblyGuide.localizedTitle",
            "private fun MealAssemblyGuide.localizedPlateStructure",
            "private fun MealAssemblyGuide.localizedProteinAnchor",
            "private fun MealAssemblyGuide.localizedCarbAnchor",
            "private fun MealAssemblyGuide.localizedFatControl",
            "private fun MealAssemblyGuide.localizedFiberMicros",
            "private fun MealAssemblyGuide.localizedShoppingCue",
            "private fun MealAssemblyGuide.localizedPrepCue",
            "private fun MealAssemblyGuide.localizedPhotoLoggingCue",
            "private fun MealAssemblyGuide.localizedAvoidCue",
            "guide.localizedTitle(language)",
            "guide.localizedPlateStructure(language)",
            "guide.localizedProteinAnchor(language)",
            "guide.localizedCarbAnchor(language)",
            "guide.localizedFatControl(language)",
            "guide.localizedFiberMicros(language)",
            "guide.localizedShoppingCue(language)",
            "guide.localizedPrepCue(language)",
            "guide.localizedPhotoLoggingCue(language)",
            "guide.localizedAvoidCue(language)",
            "BodyCompositionGuidance.localizedStatusLabel",
            "BodyCompositionGuidance.localizedPhaseGoal",
            "ConditioningHydrationGuidance.localizedStatusLabel",
            "localizedConditioningText",
            "language.t(\"Step goal\", \"步数目标\")",
            "language.t(\"Water L\", \"饮水 L\")",
            "language.t(\"Digestion, bloating, high-salt meal, cramps, pump\", \"消化、胀气、高盐餐、抽筋、泵感\")",
        ]
        for term in expected_ui_terms:
            with self.subTest(term=term):
                self.assertIn(term, ui)

        forbidden_ui_terms = [
            "Text(guide.title",
            "text = guide.plateStructure",
            "guide.proteinAnchor,",
            "guide.carbAnchor,",
            "guide.fatControl,",
            "guide.fiberMicros",
        ]
        for term in forbidden_ui_terms:
            with self.subTest(term=term):
                self.assertNotIn(term, ui)

        preview_terms = [
            'data-zh="营养节奏"',
            'data-zh="餐食记录教练"',
            'data-zh="下一餐构建器"',
            'data-zh="餐盘组合指南"',
            'data-zh="蛋白质锚点：鸡肉、白鱼、瘦牛肉、乳清、豆腐或希腊酸奶"',
            'data-zh="拍照记录提示：AI 估算前，拍下不确定的外食份量、油、酱料、标签和碗深。"',
            'data-zh="身体组成指导"',
            'data-zh="有氧、活动量与补水"',
            'data-zh="餐食模板"',
            'data-zh="添加餐食"',
            'data-zh="食物照片"',
            'data-zh="照片证据"',
            'data-zh="餐食照片估算"',
        ]
        for term in preview_terms:
            with self.subTest(term=term):
                self.assertIn(term, preview)

    def test_health_connect_integration_is_structured_and_permissioned(self) -> None:
        gradle = (APP / "app/build.gradle.kts").read_text(encoding="utf-8")
        manifest = (APP / "app/src/main/AndroidManifest.xml").read_text(encoding="utf-8")
        repository = (
            APP / "app/src/main/java/com/iwanttobeanifbbpro/app/health/HealthConnectRepository.kt"
        ).read_text(encoding="utf-8")
        snapshot = (APP / "app/src/main/java/com/iwanttobeanifbbpro/app/health/HealthSnapshot.kt").read_text(
            encoding="utf-8"
        )
        expected_terms = [
            "androidx.health.connect:connect-client",
            "android.permission.health.READ_WEIGHT",
            "android.permission.health.READ_BODY_FAT",
            "android.permission.health.READ_STEPS",
            "android.permission.health.READ_SLEEP",
            "android.permission.health.READ_RESTING_HEART_RATE",
            "com.google.android.apps.healthdata",
            "android.permission.START_VIEW_PERMISSION_USAGE",
            "android.intent.action.VIEW_PERMISSION_USAGE",
            "android.intent.category.HEALTH_PERMISSIONS",
            "HealthConnectClient",
            "import androidx.health.connect.client.PermissionController",
            "PermissionController.createRequestPermissionResultContract",
            "HealthPermission.getReadPermission",
            "WeightRecord",
            "BodyFatRecord",
            "LeanBodyMassRecord",
            "StepsRecord",
            "SleepSessionRecord",
            "RestingHeartRateRecord",
            "TotalCaloriesBurnedRecord",
            "AggregateRequest",
            "ReadRecordsRequest",
            "HealthSnapshot",
            "hasImportableMetrics",
            "Xiaomi",
            "Huawei",
            "source app writes compatible records into Health Connect",
        ]
        combined = f"{gradle}\n{manifest}\n{repository}\n{snapshot}"
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, combined)

    def test_readmes_document_four_main_app_sections_and_folded_flows(self) -> None:
        root_readme = (ROOT / "README.md").read_text(encoding="utf-8")
        zh_readme = (ROOT / "README.zh-CN.md").read_text(encoding="utf-8")
        app_readme = (APP / "README.md").read_text(encoding="utf-8")
        readmes = {
            "README.md": root_readme,
            "README.zh-CN.md": zh_readme,
            "android-app/README.md": app_readme,
        }
        common_terms = [
            "Training / 训练",
            "Nutrition / 饮食",
            "Metrics / 身体数据",
            "Today Flow Coach",
            "Plan Flow Coach",
            "Daily Coach Checklist",
            "Weekly Check-in",
        ]
        for relative, readme in readmes.items():
            for term in common_terms:
                with self.subTest(readme=relative, term=term):
                    self.assertIn(term, readme)

        english_folded_terms = [
            "four main sections",
            "`Today Flow Coach` is folded into AI",
            "`Plan Flow Coach` is folded into Training",
            "no separate `Today` or `Plan` primary tab",
        ]
        for relative, readme in {
            "README.md": root_readme,
            "android-app/README.md": app_readme,
        }.items():
            for term in english_folded_terms:
                with self.subTest(readme=relative, term=term):
                    self.assertIn(term, readme)

        zh_folded_terms = [
            "四个主区",
            "`Today Flow Coach` 折叠到 AI 的每日总览/复盘",
            "`Plan Flow Coach` 折叠到 Training 的训练计划层",
            "不再有单独的 `Today` 或 `Plan` 主 tab",
        ]
        for term in zh_folded_terms:
            with self.subTest(readme="README.zh-CN.md", term=term):
                self.assertIn(term, zh_readme)

    def test_readme_documents_build_and_api_setup(self) -> None:
        readme = (APP / "README.md").read_text(encoding="utf-8")
        expected_terms = [
            "Android Studio",
            "JDK 17",
            "API key",
            "base URL",
            "model",
            "OpenAI Responses API",
            "photos",
            "Photo Evidence",
            "classified photos",
            "food, form, equipment, label, or physique progress",
            "Food or label photo",
            "Exercise form frame",
            "Equipment photo",
            "Physique progress photo",
            "skill assets",
            "daily training",
            "daily nutrition",
            "AI review",
            "rest countdown",
            "set-level",
            "four main sections",
            "Training / 训练",
            "Nutrition / 饮食",
            "Metrics / 身体数据",
            "`Today Flow Coach` is folded into AI",
            "`Plan Flow Coach` is folded into Training",
            "no separate `Today` or `Plan` primary tab",
            "AI Data Map",
            "weekly training plan",
            "Plan Templates",
            "Plan Flow Coach",
            "showPlanDetails",
            "Training plan layers",
            "Use recommended template",
            "Template -> weekly plan -> Apply today",
            "Beginner Full Body",
            "4-Day Hypertrophy",
            "5-Day Physique Priority",
            "Apply today",
            "Health Connect",
            "Xiaomi",
            "Mi Fitness",
            "Huawei",
            "body fat",
            "resting heart rate",
            "Huawei Health Kit",
            "Athlete Profile",
            "target weight/body fat",
            "weekly training days",
            "manual entry",
            "EN/中文 language switching",
            "AppLanguage",
            "updateLanguage",
            "loadLanguage",
            "Today Flow Coach",
            "TodayFlowCoachState",
            "todayFlowCoachState",
            "daily detail layers",
            "one primary button",
            "Start Here",
            "DailyStartStep",
            "StartHereCoachCard",
            "StartHereStepRow",
            "full Start Here checklist",
            "AI Setup & Review Readiness",
            "AiSetupStatus",
            "AiSetupStatusCard",
            "AiSettings.isConfigured()",
            "missing setup",
            "AI review ready",
            "photo context",
            "unified exercise visual guide",
            "Exercise Visual Library",
            "Smith machine",
            "cable station",
            "dumbbells",
            "barbell",
            "machine",
            "adjustable bench",
            "pull-up/dip station",
            "resistance band",
            "leg press or hack squat",
            "bodyweight/open-station",
            "Chinese equipment labels",
            "instance diagram cues",
            "visual guide IDs",
            "unified instance diagrams",
            "action path cues",
            "quick visual cues",
            "find-equipment cues",
            "movement path cues",
            "beginner recognition cues",
            "equipment markers",
            "common movement examples",
            "live equipment/action preview",
            "example movement",
            "look-for cue",
            "Meal Flow Coach",
            "showNutritionDetails",
            "Prefill next meal",
            "Nutrition detail layers",
            "Nutrition Pacing",
            "Next Meal Builder",
            "next practical meal target",
            "meal timing cue",
            "portion uncertainty cue",
            "Meal Assembly Guide",
            "plate structure",
            "protein anchor",
            "carb anchor",
            "fat control",
            "shopping cue",
            "prep cue",
            "photo/logging cue",
            "Meal Templates",
            "Lean Protein Bowl",
            "Pre-Workout Carbs",
            "Low-Fat Protein Fix",
            "remaining or over target",
            "macro adherence score",
            "next-meal focus",
            "Body Composition Guidance",
            "small calorie adjustment",
            "Physique Measurement Summary",
            "waistCm",
            "chestCm",
            "shoulderCm",
            "hipCm",
            "leftArmCm",
            "rightArmCm",
            "leftThighCm",
            "rightThighCm",
            "neckCm",
            "shoulder-to-waist ratio",
            "arm symmetry",
            "thigh symmetry",
            "Recovery Guidance",
            "training-pressure guidance",
            "Metrics Flow Coach",
            "showMetricsDetails",
            "Metrics detail layers",
            "Connect health data",
            "Sync today",
            "Progress photo",
            "AI Review Flow Coach",
            "showAiDetails",
            "AI detail layers",
            "Run daily review",
            "Daily review evidence bundle",
            "Daily Execution Plan",
            "priority focus",
            "primary action",
            "data quality gate",
            "AI review gate",
            "plan adjustment signal",
            "Training Readiness Builder",
            "Warm-up Ramp Plan",
            "ramp set checklist",
            "planned load percentages",
            "final ramp set quality",
            "first working set gate",
            "Next Set Coach",
            "current exercise",
            "next set target",
            "load cue",
            "reps cue",
            "RIR cue",
            "rest cue",
            "stop cue",
            "after-set logging cue",
            "Tomorrow Coach Brief",
            "Weekly Check-in",
            "training completion",
            "average calories/protein",
            "weight change",
            "recovery average",
            "weak-point focus",
            "next-week action",
            "tomorrow training focus",
            "tomorrow nutrition target",
            "tomorrow recovery gate",
            "tomorrow tracking action",
            "readiness gate",
            "Session Quality Dashboard",
            "Training Closeout Coach",
            "closeout score",
            "missing set logs",
            "photo evidence cue",
            "post-workout nutrition cue",
            "metrics sync cue",
            "AI review readiness",
            "completion rate",
            "logged set rate",
            "average RIR",
            "muscle-volume distribution",
            "pain flags",
            "technique flags",
            "warm-up strategy",
            "first working set",
            "volume adjustment",
            "stop rule",
            "reduce volume",
            "deload check",
            "Progression Cue",
            "Exercise Substitution Coach",
            "primaryOption",
            "secondaryOptions",
            "same target muscle",
            "same movement pattern",
            "preserve rep range",
            "fatigue cost",
            "keepIntentCue",
            "loadAdjustmentCue",
            "visual guide ID continuity",
            "Exercise History",
            "previous/current volume",
            "best load",
            "best reps",
            "average RIR",
            "add reps",
            "add load",
            "hold",
            "modify",
        ]
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, readme)

    def test_static_ui_preview_covers_core_app_workflows(self) -> None:
        html_path = APP / "preview/index.html"
        readme_path = APP / "preview/README.md"
        self.assertTrue(html_path.exists(), "preview/index.html")
        self.assertTrue(readme_path.exists(), "preview/README.md")
        html = html_path.read_text(encoding="utf-8")
        readme = readme_path.read_text(encoding="utf-8")
        expected_terms = [
            "Live design preview",
            "Apple",
            "Today",
            "EN/中文",
            "Language switch",
            "language-toggle",
            "data-en",
            "data-zh",
            "setLanguage",
            "Today Flow Coach",
            "Daily detail layers",
            "NEXT BEST ACTION",
            "TODAY NEXT",
            "global-next-strip",
            "global-next-button",
            "One tap daily start: plan -> train -> eat -> sync -> review.",
            "今天下一步",
            "一键式每日开始：计划 -> 训练 -> 饮食 -> 同步 -> 复盘。",
            "quick-setup-card",
            "setup-choice-grid",
            "3-TAP SETUP GATE",
            "Goal / Days / Equipment",
            "Recommended split from setup",
            "AI uses setup: goal, training days, equipment, phase, constraints",
            "三步起始设置",
            "目标 / 天数 / 器械",
            "Start Here",
            "从这里开始",
            "DailyStartStep",
            "StartHereCoachCard",
            "StartHereStepRow",
            "AppLanguage",
            "updateLanguage",
            "AI Setup & Review Readiness",
            "AiSetupStatus",
            "AiSetupStatusCard",
            "isConfigured",
            "Set API first",
            "Missing setup",
            "AI review ready",
            "Photo context linked",
            "Command Center",
            "Daily Execution Plan",
            "AI Integrated Decision Matrix",
            "review-readiness-card",
            "readiness-row",
            "readiness-dot",
            "REVIEW READINESS",
            "Review Readiness Checklist",
            "Training evidence",
            "Nutrition evidence",
            "Metrics evidence",
            "Photo/API context",
            "Fix missing evidence before AI changes training or food",
            "复盘准备度",
            "ai-change-receipt-card",
            "change-receipt-row",
            "AI CHANGE RECEIPT",
            "What changed for next session",
            "Training changes",
            "Rest changes",
            "Nutrition changes",
            "Recovery guardrail",
            "Tracking lock",
            "Applied to next workout",
            "Held until more evidence",
            "AI 变更回执",
            "all data linked",
            "Training effect",
            "Split decision",
            "Data confidence",
            "3-day / 4-day / 5-day split decision",
            "Do not change split until",
            "Priority",
            "Primary",
            "Data quality gate",
            "AI review gate",
            "Plan adjustment signal",
            "Athlete Profile",
            "Plan Flow Coach",
            "AI Plan Adjustment Proposal",
            "Apply AI split template",
            "template proposal from linked evidence",
            "NEXT PLAN ACTION",
            "Training plan layers",
            "profile, templates, weekly plan, visual map, exercise editing",
            "Plan Templates",
            "Beginner Full Body",
            "4-Day Hypertrophy",
            "5-Day Physique Priority",
            "Weekly Plan",
            "Training Execution",
            "Workout Flow Coach",
            "one-tap-hero",
            "Today Readiness Gate",
            "Push / Hold / Reduce / Recover",
            "Training decision",
            "训练决策",
            "Fuel gate",
            "供能闸门",
            "Hold today",
            "今天保持",
            "Sleep + HR + soreness + RIR",
            "today readiness gate",
            "push hold reduce recover",
            ".side",
            "display: none",
            "Complete set + start rest",
            "AI matched rest",
            "AI Rest Prescription",
            "restSeconds auto update",
            "after AI review",
            "recommended rest",
            "next-session carryover",
            "Professional detail layers",
            "action-shortcuts",
            "exercise image slot",
            "Training Readiness Builder",
            "Warm-up Ramp Plan",
            "ramp set checklist",
            "planned load percentages",
            "final ramp set quality",
            "first working set gate",
            "Next Set Coach",
            "Current exercise",
            "Next set target",
            "Load cue",
            "RIR cue",
            "Rest cue",
            "Stop cue",
            "After-set logging cue",
            "Tomorrow Coach Brief",
            "Weekly Check-in",
            "Training completion",
            "Recovery average",
            "Weak-point focus",
            "Next week action",
            "Tomorrow training focus",
            "Tomorrow nutrition target",
            "Tomorrow recovery gate",
            "Tomorrow tracking action",
            "Readiness gate",
            "Session Quality Dashboard",
            "Training Closeout Coach",
            "closeout score",
            "missing set logs",
            "photo evidence cue",
            "post-workout nutrition cue",
            "metrics sync cue",
            "AI review readiness",
            "Completion rate",
            "Logged set rate",
            "Average RIR",
            "Muscle volume distribution",
            "Pain flags",
            "Technique flags",
            "Warm-up cue",
            "Ramp-up cue",
            "First working set",
            "Volume adjustment",
            "Stop rule",
            "Rest timer",
            "Nutrition",
            "Meal Templates",
            "Lean Protein Bowl",
            "Pre-Workout Carbs",
            "Low-Fat Protein Fix",
            "Health Connect",
            "Unified health permission",
            "Auto refresh after permission",
            "health-sync-receipt-card",
            "health-sync-row",
            "HEALTH SYNC RECEIPT",
            "Health sync receipt",
            "Imported today",
            "Missing signals",
            "AI uses sleep, weight, steps, resting HR, and calorie burn",
            "Auto refresh on app open",
            "Manual fallback still works",
            "健康同步回执",
            "Body Trend Chart",
            "AI Review Action Queue",
            "sourceLabel",
            "confidenceLabel",
            "primaryAction",
            "actionLabel",
            "training action",
            "nutrition action",
            "recovery action",
            "tracking action",
            "plan action",
            "AI Coach",
            "AI Data Map",
            "Photo Evidence",
            "Photo purpose",
            "Food or label photo",
            "Exercise form frame",
            "Equipment photo",
            "Physique progress photo",
            "Menu or nutrition label",
            "Classified photos",
            "Saved AI Reviews",
            "Daily Coach Checklist",
            "Plan prepared",
            "Training executed",
            "Food logged",
            "Metrics synced",
            "AI review locked",
            "Exercise visual guide",
            "exercise-card-v2",
            "equipment-photo",
            "muscle-badge",
            "Find this equipment first",
            "Attach equipment photo",
            "setup steps",
            "common mistakes",
            "Exercise Visual Library",
            "Exercise Visual Legend",
            "统一动作图例",
            "legend-grid",
            "legend-tile",
            "Today Visual Primer",
            "Selected Day Visual Map",
            "Today's Exercise Visual Map",
            "exercise thumbnail headers",
            "Live equipment/action preview",
            "Chinese equipment labels",
            "Visual guide ID",
            "Unified instance diagram",
            "Unified Exercise Visual Atlas",
            "Three-step recognition",
            "Simplified instance diagram",
            "Find real equipment",
            "Movement path matching",
            "Action path cue",
            "Quick visual cue",
            "Find equipment cue",
            "Movement path cue",
            "Beginner recognition cue",
            "Equipment markers",
            "Instance diagram cue",
            "Common movement examples",
            "Equipment photo recognition",
            "Exercise name -> visual category",
            "simple equipment/action instance diagrams",
            "visual-map thumbnails",
            "VG-01",
            "VG-10",
            "Smith machine",
            "Cable station",
            "Dumbbells",
            "Barbell",
            "Machine",
            "Adjustable bench",
            "Pull-up/Dip station",
            "Resistance band",
            "Leg press or hack squat",
            "Bodyweight or open station",
            "Guided press path",
            "Pulley resistance",
            "Example: Incline Smith Press",
            "史密斯机",
            "哑铃",
            "Smith Squat",
            "Dumbbell Press",
            "Look for two rails and a fixed bar",
            "Unified exercise visual guide",
            "equipment/action instance diagrams",
            "Unified Exercise Visual Atlas",
            "Three-step recognition",
            "Simplified instance diagram",
            "Find real equipment",
            "Movement path matching",
            "Meal Flow Coach",
            "nutrition-autopilot-card",
            "nutrition-step-row",
            "NUTRITION AUTOPILOT",
            "Nutrition Autopilot",
            "Eat -> Capture -> Confirm -> Review",
            "Current meal target",
            "Macro gaps",
            "Photo confidence",
            "Next nutrition action",
            "饮食自动教练",
            "NEXT MEAL ACTION",
            "Prefill next meal",
            "meal-estimate-receipt-card",
            "meal-estimate-row",
            "AI MEAL ESTIMATE",
            "Meal estimate receipt",
            "Estimated macros",
            "Confidence",
            "Logged to today",
            "Remaining after this meal",
            "Confirm portions, oil, sauce, and labels",
            "餐食估算回执",
            "Nutrition detail layers",
            "Food photo nutrition estimate",
            "Nutrition Pacing",
            "Next Meal Builder",
            "Next meal macro targets",
            "Meal Assembly Guide",
            "Plate structure",
            "Protein anchor",
            "Carb anchor",
            "Fat control",
            "Fiber/micros",
            "Shopping cue",
            "Prep cue",
            "Photo/logging cue",
            "Meal timing cue",
            "Portion uncertainty cue",
            "Meal Templates",
            "Body Composition Guidance",
            "Physique Measurement Summary",
            "Metrics Flow Coach",
            "metrics-autopilot-card",
            "metrics-step-row",
            "METRICS AUTOPILOT",
            "Metrics Autopilot",
            "Sync -> Trend -> Photo -> Review",
            "Trend confidence",
            "Sleep and recovery",
            "Health permission",
            "Next metrics action",
            "身体数据自动教练",
            "NEXT METRICS ACTION",
            "Metrics detail layers",
            "health sync, recovery, measurements, photos, trend",
            "Sync today",
            "Progress photo",
            "AI Review Flow Coach",
            "NEXT AI REVIEW ACTION",
            "Run daily review",
            "AI detail layers",
            "setup, photos, prompt, data map, history",
            "daily review evidence",
            "daily-autopilot-card",
            "autopilot-step-row",
            "DAILY AUTOPILOT",
            "Daily Autopilot",
            "Follow this order today",
            "Train -> Eat -> Sync -> Review",
            "Current next step",
            "Today's evidence gaps",
            "Autopilot action",
            "One screen daily loop",
            "每日自动教练",
            "训练 -> 饮食 -> 同步 -> 复盘",
            "Physique Measurements",
            "Chest cm",
            "Shoulder cm",
            "Left arm cm",
            "Right thigh cm",
            "shoulder-to-waist ratio",
            "arm symmetry",
            "thigh symmetry",
            "Recovery Guidance",
            "Training Readiness Builder",
            "Warm-up Ramp Plan",
            "Warm-up cue",
            "Ramp-up cue",
            "Ramp set checklist",
            "planned load percentage",
            "final ramp set quality",
            "first working set gate",
            "First working set",
            "Volume adjustment",
            "Stop rule",
            "Training action",
            "Sleep signal",
            "HR signal",
            "Hold targets",
            "Kcal adjust",
            "Weight trend",
            "Next meal focus",
            "Nutrition totals + pacing",
            "Body Composition Guidance",
            "Protein behind",
            "Progression Cue",
            "Exercise Substitution Coach",
            "equipment unavailable",
            "trigger reason",
            "primaryOption",
            "secondaryOptions",
            "same target muscle",
            "same movement pattern",
            "preserve rep range",
            "fatigue cost",
            "keepIntentCue",
            "loadAdjustmentCue",
            "Exercise History",
            "Add reps first",
            "Last volume",
            "Today volume",
            "Best load",
            "Best reps",
            "Avg RIR",
            "previous/current volume",
            "data-tab",
            "complete-set",
            "setInterval",
            "Open `index.html`",
        ]
        combined = f"{html}\n{readme}"
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, combined)
        self.assertIn('<section class="panel" data-panel="ai" aria-label="AI Coach">', html)
        self.assertIn('<section class="folded-panel" data-folded-panel="ai" aria-label="AI daily overview" hidden>', html)
        self.assertIn('<section class="folded-panel" data-folded-panel="training" aria-label="Training plan" hidden>', html)
        self.assertIn("mountFoldedPanels", html)
        self.assertEqual(
            ["training", "nutrition", "metrics", "ai"],
            re.findall(r'<section class="panel(?: active)?" data-panel="([^"]+)"', html),
        )

    def test_skill_assets_define_exercise_visual_guide_categories(self) -> None:
        skill_library = (ROOT / "skills/i-want-to-be-an-ifbb-pro/references/exercise-library.md").read_text(
            encoding="utf-8"
        )
        app_library = (APP / "app/src/main/assets/skill/references/exercise-library.md").read_text(
            encoding="utf-8"
        )
        visual_analysis = (
            ROOT / "skills/i-want-to-be-an-ifbb-pro/references/visual-analysis-and-food-estimation.md"
        ).read_text(encoding="utf-8")
        app_visual_analysis = (
            APP / "app/src/main/assets/skill/references/visual-analysis-and-food-estimation.md"
        ).read_text(encoding="utf-8")
        nutrition_body_composition = (
            ROOT / "skills/i-want-to-be-an-ifbb-pro/references/nutrition-body-composition.md"
        ).read_text(encoding="utf-8")
        app_nutrition_body_composition = (
            APP / "app/src/main/assets/skill/references/nutrition-body-composition.md"
        ).read_text(encoding="utf-8")
        session_execution = (
            ROOT / "skills/i-want-to-be-an-ifbb-pro/references/session-execution-and-volume.md"
        ).read_text(encoding="utf-8")
        app_session_execution = (
            APP / "app/src/main/assets/skill/references/session-execution-and-volume.md"
        ).read_text(encoding="utf-8")
        expected_terms = [
            "Exercise Visual Guide",
            "Chinese equipment labels",
            "simple instance diagrams",
            "Unified Exercise Visual Atlas",
            "three-step recognition",
            "Match the simplified instance diagram",
            "Find the real equipment markers",
            "Follow the intended movement path",
            "quick visual cues",
            "find-equipment cues",
            "movement path cues",
            "visual IDs",
            "VG-01",
            "VG-10",
            "Unified instance diagram",
            "Action path cue",
            "Beginner cue",
            "Equipment markers",
            "instance diagram cue",
            "common movements",
            "Smith machine",
            "史密斯机",
            "Cable station",
            "绳索龙门架/滑轮器械",
            "Dumbbells",
            "哑铃",
            "Barbell",
            "杠铃",
            "Machine",
            "固定轨迹器械",
            "Bodyweight or open station",
            "自重/开放训练空间",
            "guided incline press path",
            "align bench under the fixed bar path",
            "example movement",
            "look-for cue",
            "Common movements",
            "Look for two rails and a fixed bar",
            "Selected Day Visual Map",
            "Today's Exercise Visual Map",
            "exercise thumbnail headers",
            "Adjustable bench",
            "可调训练凳",
            "Pull-up/Dip station",
            "引体向上/双杠训练站",
            "Resistance band",
            "弹力带",
            "Leg press or hack squat",
            "腿举/哈克深蹲器械",
            "Look for a flat or adjustable bench",
            "Look for an overhead bar, dip handles, or assist platform",
            "Look for a band anchored to a rack, door, or post",
            "Look for a sled platform, seat, and safety handles",
            "Map the visible setup to the Exercise Visual Guide",
            "closest VG visual guide ID",
            "quick visual cue, find-equipment cue, and movement path cue",
            "Exercise Substitution Coach",
            "primaryOption",
            "secondaryOptions",
            "same target muscle",
            "same movement pattern",
            "planned rep range",
            "fatigue cost",
            "load-adjustment cue",
            "visual guide ID",
            "Warm-up Ramp Plan",
            "warm-up ramp set checklist",
            "planned working load",
            "final ramp set",
            "first working set gate",
            "Do not count warm-up ramp sets as hard sets",
            "Training Closeout Coach",
            "closeout score",
            "missing set logs",
            "form/equipment photo evidence",
            "post-workout nutrition",
            "Health Connect sync",
            "AI review readiness",
            "waistCm",
            "chestCm",
            "shoulderCm",
            "hipCm",
            "leftArmCm",
            "rightArmCm",
            "leftThighCm",
            "rightThighCm",
            "neckCm",
            "shoulder-to-waist ratio",
            "arm symmetry",
            "thigh symmetry",
        ]
        combined = f"{skill_library}\n{app_library}\n{visual_analysis}\n{app_visual_analysis}\n{nutrition_body_composition}\n{app_nutrition_body_composition}\n{session_execution}\n{app_session_execution}"
        for term in expected_terms:
            with self.subTest(term=term):
                self.assertIn(term, combined)


if __name__ == "__main__":
    unittest.main()
